-- DVLP_RAPTOR_NEWADJ_3.FACT.STRESS_MEASURES_ADJUSTMENT definition

create or replace TABLE DVLP_RAPTOR_NEWADJ_3.FACT.STRESS_MEASURES_ADJUSTMENT (
	COBID NUMBER(38,0) NOT NULL,
	REGION_AREA_KEY NUMBER(38,0),
	ENTITY_KEY NUMBER(38,0) NOT NULL,
	TRADE_KEY NUMBER(38,0) NOT NULL,
	BOOK_KEY NUMBER(38,0) NOT NULL,
	TRADE_CURRENCY VARCHAR(3) NOT NULL COLLATE 'en-ci',
	COMMON_INSTRUMENT_KEY NUMBER(38,0) NOT NULL,
	COMMON_INSTRUMENT_FCD_KEY NUMBER(38,0) NOT NULL,
	COUNTERPARTY_KEY NUMBER(38,0) NOT NULL,
	PRODUCT_CATEGORY_ATTRIBUTES_KEY NUMBER(38,0),
	ADJUSTMENT_ID NUMBER(38,0) NOT NULL,
	STRESS_SIMULATION_KEY NUMBER(38,0) NOT NULL,
	SOURCE_SYSTEM_CODE VARCHAR(2) NOT NULL COLLATE 'en-ci',
	IS_OFFICIAL_SOURCE BOOLEAN,
	SIMULATION_PL_IN_USD NUMBER(38,6) NOT NULL,
	LOAD_SET VARCHAR(100) COLLATE 'en-ci',
	RUN_LOG_ID NUMBER(38,0)
);