-- DVLP_RAPTOR_NEWADJ_3.FACT.VAR_MEASURES_ADJUSTMENT definition

create or replace TABLE DVLP_RAPTOR_NEWADJ_3.FACT.VAR_MEASURES_ADJUSTMENT (
	COBID NUMBER(38,0) NOT NULL,
	VAR_SUBCOMPONENT_ID NUMBER(38,0) NOT NULL,
	ADJUSTMENT_ID NUMBER(38,0) NOT NULL,
	BOOK_KEY NUMBER(38,0) NOT NULL,
	TRADE_KEY NUMBER(38,0) NOT NULL,
	CURRENCY_CODE VARCHAR(3) NOT NULL COLLATE 'en-ci',
	SOURCE_SYSTEM_CODE VARCHAR(2) NOT NULL COLLATE 'en-ci',
	ENTITY_CODE VARCHAR(10) NOT NULL COLLATE 'en-ci',
	INFLATION_INDEX_ID NUMBER(38,0) NOT NULL,
	COMMON_INSTRUMENT_KEY NUMBER(38,0) NOT NULL,
	UNDERLYING_COMMON_INSTRUMENT_KEY NUMBER(38,0) NOT NULL,
	IS_OFFICIAL_SOURCE BOOLEAN,
	REGION_AREA_KEY NUMBER(38,0) NOT NULL,
	SCENARIO_DATE_ID NUMBER(38,0) NOT NULL,
	PNL_VECTOR_VALUE_IN_USD NUMBER(19,4) NOT NULL,
	RUN_LOG_ID NUMBER(38,0) NOT NULL,
	COMMON_INSTRUMENT_FCD_KEY NUMBER(38,0),
	COUNTERPARTY_KEY NUMBER(38,0) NOT NULL DEFAULT -1
);