create or replace task DVLP_RAPTOR_NEWADJ.STAGING.LOAD_FRTB_SENSITIVITY_SCALING_ADJUSTMENT_TASK
	USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL'
	after DVLP_RAPTOR_NEWADJ.STAGING.PUBLISH_SCALING_ADJUSTMENT_TASK
	as BEGIN
    INSERT INTO RAVEN.LOG_STAGE_ME_STATUS (ID,RAVEN_COBID,DATASET_NAME,PROCESS_STATUS,START_TIMESTAMP,END_TIMESTAMP)
    SELECT 
        hash(CURRENT_TIMESTAMP(),MAX(cobid),'DUMMY_FRTBSA_Adjustment',random()) AS ID, 
        MAX(COBID) AS RAVEN_COBID, 
        'DUMMY_'||PROCESS_TYPE||'_Adjustment' AS DATASET_NAME, 
        'SUCCESS' AS PROCESS_STATUS,
        CURRENT_TIMESTAMP() AS START_TIMESTAMP,
        CURRENT_TIMESTAMP() AS END_TIMESTAMP
    FROM DIMENSION.ADJUSTMENT 
    WHERE RUN_STATUS = 'Pending' 
    AND PROCESS_TYPE IN ('Sensitivity','FRTB')
    GROUP BY COBID,RUN_STATUS,DATASET_NAME;
END;