create or replace task DVLP_RAPTOR_NEWADJ.STAGING.LOAD_STRESS_SCALING_ADJUSTMENT_TASK
	warehouse=PROD_RAPTOR_WH_M
	after DVLP_RAPTOR_NEWADJ.STAGING.PUBLISH_SCALING_ADJUSTMENT_TASK
	as CALL FACT.PROCESS_ADJUSTMENTS('STRESS','0');