create or replace task DVLP_RAPTOR_NEWADJ.STAGING.LOAD_VAR_ADJUSTMENT_UPLOAD_TASK
	warehouse=PROD_RAPTOR_WH_XS
	after DVLP_RAPTOR_NEWADJ.STAGING.PUBLISH_VAR_UPLOAD_TASK
	as CALL FACT.LOAD_VAR_ADJUSTMENT_UPLOAD('0');