create or replace task DVLP_RAPTOR_NEWADJ.STAGING.GLOBAL_ADJUSTMENT_SF_TASK
	warehouse=PROD_RAPTOR_WH
	schedule='1 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM')
	as MERGE INTO ADJUSTMENT.GLOBAL_ADJUSTMENT_SF AS tgt
USING STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM_DATA AS src 
ON tgt.ADJUSTMENT_ID=src.ADJUSTMENT_ID
WHEN MATCHED AND (src.DML_TYPE = 'U' OR src.DML_TYPE = 'I')  THEN UPDATE
SET
     tgt.SOURCE_COBID=src.SOURCE_COBID
    ,tgt.APPROVAL_ID=src.APPROVAL_ID
    ,tgt.ADJUSTMENT_TYPE=src.ADJUSTMENT_TYPE
    ,tgt.REASON=src.REASON
    ,tgt.FORM_DATA=src.FORM_DATA
    ,tgt.ADJUSTED_BY=src.ADJUSTED_BY
    ,tgt.ADJUSTMENT_CREATED=src.ADJUSTMENT_CREATED
    ,tgt.ADJUSTMENT_COMPLETED=src.ADJUSTMENT_COMPLETED
    ,tgt.STATUS=src.STATUS
    ,tgt.ENTITY_CODE=src.ENTITY_CODE
    ,tgt.ENTITY_KEY=src.ENTITY_KEY
    ,tgt.DEPARTMENT_CODE=src.DEPARTMENT_CODE
    ,tgt.IS_DELETED=src.IS_DELETED
    ,tgt.DELETED_BY=src.DELETED_BY
    ,tgt.ADJUSTMENT_DELETED=src.ADJUSTMENT_DELETED
    ,tgt.TEMP_ID=src.TEMP_ID
    ,ADJUSTMENT_UPDATED = convert_timezone('Europe/London', current_timestamp)::TIMESTAMP_TZ
WHEN NOT MATCHED AND src.DML_TYPE = 'I'
THEN INSERT 
(
    COBID,ADJUSTMENT_ID, SOURCE_COBID, APPROVAL_ID, ADJUSTMENT_TYPE, REASON, FORM_DATA, 
    ADJUSTED_BY, ADJUSTMENT_CREATED, ADJUSTMENT_COMPLETED, STATUS, ENTITY_CODE, ENTITY_KEY, 
    DEPARTMENT_CODE, IS_DELETED, DELETED_BY, ADJUSTMENT_DELETED, TEMP_ID, ADJUSTMENT_UPDATED
)
VALUES 
(
    src.COBID, src.ADJUSTMENT_ID, src.SOURCE_COBID, src.APPROVAL_ID, src.ADJUSTMENT_TYPE, src.REASON, src.FORM_DATA, 
    src.ADJUSTED_BY, src.ADJUSTMENT_CREATED, src.ADJUSTMENT_COMPLETED, src.STATUS, src.ENTITY_CODE, src.ENTITY_KEY, 
    src.DEPARTMENT_CODE, src.IS_DELETED, src.DELETED_BY, src.ADJUSTMENT_DELETED, src.TEMP_ID, convert_timezone('Europe/London', current_timestamp)::TIMESTAMP_TZ
);