-- =============================================================================
-- 13_DIRECT_VALIDATION.SQL — per-scope validation views for Direct Adjustment
-- One view per scope over ADJ_DIRECT_STAGE. Generic rules v1:
--   • required fields present (config-driven via DIRECT_ACCEPTED_COLUMNS)
--   • VALUE_USD numeric and <> 0
--   • every supplied code exists in its dimension (case-insensitive)
--
-- STRUCTURE (why LEFT JOINs, not EXISTS): Snowflake rejects correlated
-- subqueries inside select-list expressions ("Unsupported subquery type
-- cannot be evaluated"), so every check is an uncorrelated LEFT JOIN
-- against a DISTINCT code set — a NULL join hit means "unknown code".
-- The entity/department-qualified BOOK and DEPARTMENT checks (whose
-- predicates depend on other stage columns) are pre-grouped per stage row
-- (ok_book / ok_dept) so they cannot fan out the outer row set.
--
-- FRTB cross-field rules will be added to the three FRTB views ONLY, when the
-- requirements arrive — that is why each scope has its own view.
-- =============================================================================
USE SCHEMA ADJUSTMENT_APP;

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_STRESS
    COMMENT = 'Row validation for Stress Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'Stress' AND IS_ACTIVE
),
ok_entity  AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade   AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
               WHERE IS_CURRENT_ROW = TRUE),
ok_instr   AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
               FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_simname AS (SELECT DISTINCT UPPER(STRESS_SIMULATION_NAME) SN
               FROM DIMENSION.STRESS_SIMULATION),
ok_simsrc  AS (SELECT DISTINCT UPPER(SIMULATION_SOURCE) SS
               FROM DIMENSION.STRESS_SIMULATION),
ok_simpair AS (SELECT DISTINCT UPPER(STRESS_SIMULATION_NAME) SN,
                      UPPER(SIMULATION_SOURCE) SS
               FROM DIMENSION.STRESS_SIMULATION),
ok_pca     AS (SELECT DISTINCT UPPER(REPLACE(PCA_CONCAT_KEY, ' ', '')) PK
               FROM DIMENSION.PRODUCT_CATEGORY_ATTRIBUTES),
-- Book/department checks depend on the row's own entity/department values,
-- so they are pre-aggregated per stage row (one flag row max — no fanout).
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL),
            IFF(s.SIMULATION_NAME IS NOT NULL AND osn.SN IS NULL,
                'Unknown SIMULATION_NAME: ' || s.SIMULATION_NAME, NULL),
            IFF(s.SIMULATION_SOURCE IS NOT NULL AND oss.SS IS NULL,
                'Unknown SIMULATION_SOURCE: ' || s.SIMULATION_SOURCE, NULL),
            IFF(s.SIMULATION_NAME IS NOT NULL AND s.SIMULATION_SOURCE IS NOT NULL
                AND osn.SN IS NOT NULL AND oss.SS IS NOT NULL AND osp.SN IS NULL,
                'SIMULATION_NAME ''' || s.SIMULATION_NAME ||
                ''' does not belong to SIMULATION_SOURCE ''' || s.SIMULATION_SOURCE || '''', NULL),
            IFF(s.PRODUCT_CATEGORY_ATTRIBUTES IS NOT NULL AND op.PK IS NULL,
                'Unknown PRODUCT_CATEGORY_ATTRIBUTES: ' || s.PRODUCT_CATEGORY_ATTRIBUTES, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity  oe  ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book    ob  ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept    od  ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade   ot  ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr   oi  ON oi.IC = UPPER(s.INSTRUMENT_CODE)
    LEFT JOIN ok_simname osn ON osn.SN = UPPER(s.SIMULATION_NAME)
    LEFT JOIN ok_simsrc  oss ON oss.SS = UPPER(s.SIMULATION_SOURCE)
    LEFT JOIN ok_simpair osp ON osp.SN = UPPER(s.SIMULATION_NAME)
                            AND osp.SS = UPPER(s.SIMULATION_SOURCE)
    LEFT JOIN ok_pca     op  ON op.PK = UPPER(REPLACE(s.PRODUCT_CATEGORY_ATTRIBUTES, ' ', ''))
);

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_SENSITIVITY
    COMMENT = 'Row validation for Sensitivity Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'Sensitivity' AND IS_ACTIVE
),
ok_entity  AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade   AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
               WHERE IS_CURRENT_ROW = TRUE),
ok_instr   AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
               FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_mt      AS (SELECT DISTINCT UPPER(MEASURE_TYPE_CODE) MC
               FROM DIMENSION.MEASURE_TYPE),
ok_tenor   AS (SELECT DISTINCT UPPER(TENOR_CURRENCY_CODE) TCC
               FROM DIMENSION.TENOR_CURRENCY),
ok_curve   AS (SELECT DISTINCT UPPER(CURVE_CODE) CC
               FROM DIMENSION.CURVE_CURRENCY),
ok_pca     AS (SELECT DISTINCT UPPER(REPLACE(PCA_CONCAT_KEY, ' ', '')) PK
               FROM DIMENSION.PRODUCT_CATEGORY_ATTRIBUTES),
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL),
            IFF(s.TENOR_CODE IS NOT NULL AND otc.TCC IS NULL,
                'Unknown TENOR_CODE (for currency): ' || s.TENOR_CODE, NULL),
            IFF(s.CURVE_CODE IS NOT NULL AND oc.CC IS NULL,
                'Unknown CURVE_CODE: ' || s.CURVE_CODE, NULL),
            IFF(s.MEASURE_TYPE_CODE IS NOT NULL AND om.MC IS NULL,
                'Unknown MEASURE_TYPE_CODE: ' || s.MEASURE_TYPE_CODE, NULL),
            IFF(s.PRODUCT_CATEGORY_ATTRIBUTES IS NOT NULL AND op.PK IS NULL,
                'Unknown PRODUCT_CATEGORY_ATTRIBUTES: ' || s.PRODUCT_CATEGORY_ATTRIBUTES, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity oe  ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book   ob  ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept   od  ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade  ot  ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr  oi  ON oi.IC = UPPER(s.INSTRUMENT_CODE)
    LEFT JOIN ok_tenor  otc ON otc.TCC = UPPER(CONCAT(s.TENOR_CODE, '_',
                                    COALESCE(s.CURRENCY_CODE, 'USD')))
    LEFT JOIN ok_curve  oc  ON oc.CC = UPPER(s.CURVE_CODE)
    LEFT JOIN ok_mt     om  ON om.MC = UPPER(s.MEASURE_TYPE_CODE)
    LEFT JOIN ok_pca    op  ON op.PK = UPPER(REPLACE(s.PRODUCT_CATEGORY_ATTRIBUTES, ' ', ''))
);

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_VAR
    COMMENT = 'Row validation for VaR Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'VaR' AND IS_ACTIVE
),
ok_entity AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade  AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
              WHERE IS_CURRENT_ROW = TRUE),
ok_instr  AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
              FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity oe ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book   ob ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept   od ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade  ot ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr  oi ON oi.IC = UPPER(s.INSTRUMENT_CODE)
);

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_FRTB
    COMMENT = 'Row validation for FRTB Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'FRTB' AND IS_ACTIVE
),
ok_entity AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade  AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
              WHERE IS_CURRENT_ROW = TRUE),
ok_instr  AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
              FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_mt     AS (SELECT DISTINCT UPPER(MEASURE_TYPE_CODE) MC
              FROM DIMENSION.MEASURE_TYPE),
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        -- FRTB cross-field validation rules land HERE (requirements pending)
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL),
            IFF(s.MEASURE_TYPE_CODE IS NOT NULL AND om.MC IS NULL,
                'Unknown MEASURE_TYPE_CODE: ' || s.MEASURE_TYPE_CODE, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity oe ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book   ob ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept   od ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade  ot ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr  oi ON oi.IC = UPPER(s.INSTRUMENT_CODE)
    LEFT JOIN ok_mt     om ON om.MC = UPPER(s.MEASURE_TYPE_CODE)
);

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_FRTBDRC
    COMMENT = 'Row validation for FRTBDRC Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'FRTBDRC' AND IS_ACTIVE
),
ok_entity AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade  AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
              WHERE IS_CURRENT_ROW = TRUE),
ok_instr  AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
              FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_mt     AS (SELECT DISTINCT UPPER(MEASURE_TYPE_CODE) MC
              FROM DIMENSION.MEASURE_TYPE),
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        -- FRTB cross-field validation rules land HERE (requirements pending)
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL),
            IFF(s.MEASURE_TYPE_CODE IS NOT NULL AND om.MC IS NULL,
                'Unknown MEASURE_TYPE_CODE: ' || s.MEASURE_TYPE_CODE, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity oe ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book   ob ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept   od ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade  ot ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr  oi ON oi.IC = UPPER(s.INSTRUMENT_CODE)
    LEFT JOIN ok_mt     om ON om.MC = UPPER(s.MEASURE_TYPE_CODE)
);

CREATE OR REPLACE VIEW ADJUSTMENT_APP.VW_DIRECT_VALIDATE_FRTBRRAO
    COMMENT = 'Row validation for FRTBRRAO Direct Adjustment staging rows.'
AS
WITH req AS (
    SELECT
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'ENTITY_CODE', 1, 0)) AS REQ_ENTITY,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'VALUE_USD',  1, 0)) AS REQ_VALUE,
        MAX(IFF(IS_REQUIRED AND STAGE_COLUMN = 'BOOK_CODE',  1, 0)) AS REQ_BOOK
    FROM ADJUSTMENT_APP.DIRECT_ACCEPTED_COLUMNS
    WHERE PROCESS_TYPE = 'FRTBRRAO' AND IS_ACTIVE
),
ok_entity AS (SELECT DISTINCT UPPER(ENTITY_CODE) EC FROM DIMENSION.ENTITY),
ok_trade  AS (SELECT DISTINCT UPPER(TRADE_CODE) TC FROM DIMENSION.TRADE
              WHERE IS_CURRENT_ROW = TRUE),
ok_instr  AS (SELECT DISTINCT UPPER(INSTRUMENT_CODE) IC
              FROM DIMENSION.COMMON_INSTRUMENT WHERE IS_CURRENT_ROW = TRUE),
ok_mt     AS (SELECT DISTINCT UPPER(MEASURE_TYPE_CODE) MC
              FROM DIMENSION.MEASURE_TYPE),
ok_book AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.BOOK_CODE) = UPPER(s2.BOOK_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
     AND (s2.DEPARTMENT_CODE IS NULL OR UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
),
ok_dept AS (
    SELECT s2.BATCH_ID, s2.ROW_NUM
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s2
    JOIN DIMENSION.BOOK b
      ON UPPER(b.DEPARTMENT_CODE) = UPPER(s2.DEPARTMENT_CODE)
     AND b.IS_CURRENT_ROW = TRUE
     AND (s2.ENTITY_CODE IS NULL OR UPPER(b.ENTITY_CODE) = UPPER(s2.ENTITY_CODE))
    GROUP BY s2.BATCH_ID, s2.ROW_NUM
)
SELECT BATCH_ID, ROW_NUM,
       ARRAY_SIZE(ERRS) = 0 AS IS_VALID,
       ERRS                 AS VALIDATION_ERRORS
FROM (
    SELECT
        s.BATCH_ID, s.ROW_NUM,
        -- FRTB cross-field validation rules land HERE (requirements pending)
        ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(s.ENTITY_CODE IS NULL AND req.REQ_ENTITY = 1,
                'ENTITY_CODE is required', NULL),
            IFF(s.VALUE_USD IS NULL AND req.REQ_VALUE = 1,
                'VALUE_USD is required', NULL),
            IFF(s.BOOK_CODE IS NULL AND COALESCE(req.REQ_BOOK, 0) = 1,
                'BOOK_CODE is required', NULL),
            IFF(s.VALUE_USD IS NOT NULL AND TRY_TO_NUMBER(s.VALUE_USD, 38, 6) IS NULL,
                'VALUE_USD is not numeric: ' || s.VALUE_USD, NULL),
            IFF(TRY_TO_NUMBER(s.VALUE_USD, 38, 6) = 0,
                'VALUE_USD must not be zero', NULL),
            IFF(s.ENTITY_CODE IS NOT NULL AND oe.EC IS NULL,
                'Unknown ENTITY_CODE: ' || s.ENTITY_CODE, NULL),
            IFF(s.BOOK_CODE IS NOT NULL AND ob.ROW_NUM IS NULL,
                'Unknown BOOK_CODE (for entity/department): ' || s.BOOK_CODE, NULL),
            IFF(s.DEPARTMENT_CODE IS NOT NULL AND od.ROW_NUM IS NULL,
                'Unknown DEPARTMENT_CODE (for entity): ' || s.DEPARTMENT_CODE, NULL),
            IFF(s.TRADE_CODE IS NOT NULL AND ot.TC IS NULL,
                'Unknown TRADE_CODE: ' || s.TRADE_CODE, NULL),
            IFF(s.INSTRUMENT_CODE IS NOT NULL AND oi.IC IS NULL,
                'Unknown INSTRUMENT_CODE: ' || s.INSTRUMENT_CODE, NULL),
            IFF(s.MEASURE_TYPE_CODE IS NOT NULL AND om.MC IS NULL,
                'Unknown MEASURE_TYPE_CODE: ' || s.MEASURE_TYPE_CODE, NULL)
        )) AS ERRS
    FROM ADJUSTMENT_APP.ADJ_DIRECT_STAGE s
    CROSS JOIN req
    LEFT JOIN ok_entity oe ON oe.EC = UPPER(s.ENTITY_CODE)
    LEFT JOIN ok_book   ob ON ob.BATCH_ID = s.BATCH_ID AND ob.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_dept   od ON od.BATCH_ID = s.BATCH_ID AND od.ROW_NUM = s.ROW_NUM
    LEFT JOIN ok_trade  ot ON ot.TC = UPPER(s.TRADE_CODE)
    LEFT JOIN ok_instr  oi ON oi.IC = UPPER(s.INSTRUMENT_CODE)
    LEFT JOIN ok_mt     om ON om.MC = UPPER(s.MEASURE_TYPE_CODE)
);
