create or replace view DVLP_RAPTOR_NEWADJ.METADATA.VW_POWERBI_ACTION_INSERT_SOURCE(
	WORKSPACE_NAME,
	DATASET_NAME,
	OBJECT_NAME,
	OBJECT_TYPE,
	ACTION_TYPE,
	PARTITION_TYPE,
	APPLY_POLICY,
	POLICY_EFFECTIVE_DATE,
	ORIGINAL_COBID,
	COBID,
	INSERT_SOURCE,
	MAX_RUN_LOG_ID,
	MAX_RUN_LOG_TIME,
	PUBLISH_INFO
) as
WITH raw_sql AS
(
  --We need to check for each COB but only want to add a single action per powerbi object (putting the latest COB by default)
  SELECT row_number() over( partition by ppd.original_cobid, ppd.insert_source, ppd.POWERBI_OBJECT_TYPE, ppd.POWERBI_OBJECT_NAME order by cobid desc) SEQ_ID,
  x.WORKSPACE_NAME, x.DATASET_NAME , PPD.POWERBI_OBJECT_NAME AS OBJECT_NAME, PPD.POWERBI_OBJECT_TYPE AS OBJECT_TYPE, x.ACTION_TYPE, x.PARTITION_TYPE, x.APPLY_POLICY, x.POLICY_EFFECTIVE_DATE
  , PPD.ORIGINAL_COBID, PPD.COBID, PPD.INSERT_SOURCE, PPD.MAX_RUN_LOG_ID, PPD.MAX_INSERT_TIME AS MAX_RUN_LOG_TIME
  , PPI.PUBLISH_INFO
  FROM 
  (
      SELECT BDR.ORIGINAL_COBID, D.COBID, D.INSERT_SOURCE, D.POWERBI_OBJECT_TYPE, D.POWERBI_OBJECT_NAME, MAX(D.MAX_RUN_LOG_ID) AS MAX_RUN_LOG_ID, MAX(D.INSERT_TIME) MAX_INSERT_TIME, pt.PUBLISH_TYPE,
              CASE 
            WHEN D.POWERBI_OBJECT_NAME LIKE '%var%' THEN 'var' 
            WHEN D.POWERBI_OBJECT_NAME LIKE '%stress%' THEN 'stress'
            WHEN D.POWERBI_OBJECT_NAME LIKE '%sensitivity%' THEN 'sensitivity'
            WHEN D.INSERT_SOURCE LIKE '%var%' THEN 'var' 
            WHEN D.INSERT_SOURCE LIKE '%stress%' THEN 'stress'
            WHEN D.INSERT_SOURCE LIKE '%sensitivity%' THEN 'sensitivity'
        END AS DATA_GROUP_NAME
      FROM METADATA.POWERBI_PUBLISH_DETAIL d
            INNER JOIN METADATA.VW_BUSINESS_DAY_RANGE BDR
            ON BDR.COBID = d.COBID AND BDR.BUSINESS_DAYS_IN_PAST <= 3
            LEFT OUTER JOIN METADATA.POWERBI_PUBLISH_TYPE pt
            ON d.POWERBI_OBJECT_NAME = pt.POWERBI_OBJECT_NAME
      GROUP BY BDR.ORIGINAL_COBID, d.COBID, d.INSERT_SOURCE, d.POWERBI_OBJECT_TYPE, d.POWERBI_OBJECT_NAME, pt.PUBLISH_TYPE
  ) PPD
  INNER JOIN
  (            
      SELECT pdr.WORKSPACE_NAME, pdr.DATASET_NAME, pdr.DATA_GROUP_NAME
          , 'P' ACTION_TYPE, NULL PARTITION_TYPE
          , 'Y' APPLY_POLICY, NULL POLICY_EFFECTIVE_DATE
      FROM METADATA.POWERBI_DATA_RETENTION pdr
      WHERE
      pdr.DATASET_NAME = 'RaptorReporting'
      AND pdr.DATA_GROUP_NAME IN ( 'var' , 'stress', 'sensitivity' )
  ) x on x.data_group_name = ppd.data_group_name
  LEFT JOIN 
  (
  SELECT ORIGINAL_COBID, DATASET_NAME, DATA_GROUP_NAME, PUBLISH_INFO
  FROM METADATA.VW_PUBLISH_INFO_JSON
  ) ppi
  ON PPD.ORIGINAL_COBID = ppi.ORIGINAL_COBID
  AND x.DATASET_NAME = ppi.DATASET_NAME
  AND x.DATA_GROUP_NAME = ppi.DATA_GROUP_NAME
  WHERE 
  /*
      No action waiting with the same parameters
  */
  NOT EXISTS
  (
      SELECT 1
      FROM METADATA.POWERBI_ACTION a
      WHERE
      a.ACTION_STATUS = 'W'
      AND a.DATASET_NAME = x.DATASET_NAME
      AND a.OBJECT_NAME = PPD.POWERBI_OBJECT_NAME
      AND a.OBJECT_TYPE = PPD.POWERBI_OBJECT_TYPE
      AND a.ACTION_TYPE = x.ACTION_TYPE
      AND NVL(a.PARTITION_TYPE,'') = NVL(x.PARTITION_TYPE,'')
      AND NVL(a.APPLY_POLICY,'') = NVL(x.APPLY_POLICY,'')
      AND NVL(a.POLICY_EFFECTIVE_DATE,'1900-01-01') = NVL(x.POLICY_EFFECTIVE_DATE,'1900-01-01')
  )
  /*
      No action with the same parameters with the same or newer runlog
  */
  AND NOT EXISTS 
  (
      SELECT 1
      FROM METADATA.POWERBI_ACTION r
          , LATERAL flatten (INPUT => r.PUBLISH_INFO:COBS) inf
          , LATERAL flatten (INPUT => inf.VALUE:PUBLISH_INFO[0]) res
      WHERE
      r.DATASET_NAME = x.DATASET_NAME
      AND r.OBJECT_NAME = PPD.POWERBI_OBJECT_NAME
      AND r.OBJECT_TYPE = PPD.POWERBI_OBJECT_TYPE
      AND r.ACTION_TYPE = x.ACTION_TYPE
      AND NVL(r.PARTITION_TYPE,'') = NVL(x.PARTITION_TYPE,'')
      AND NVL(r.APPLY_POLICY,'') = NVL(x.APPLY_POLICY,'')
      AND NVL(r.POLICY_EFFECTIVE_DATE,'1900-01-01') = NVL(x.POLICY_EFFECTIVE_DATE,'1900-01-01')
      AND inf.VALUE:COBID::NUMERIC = PPD.COBID
      AND res.PATH = ppd.PUBLISH_TYPE
      AND to_timestamp_tz(res.VALUE::varchar) >= ppd.MAX_INSERT_TIME
  )
  /*
      No dataset action waiting
  */
  AND NOT EXISTS
  (
      SELECT 1
      FROM METADATA.POWERBI_ACTION a
      WHERE
      a.ACTION_STATUS = 'W'
      AND a.DATASET_NAME = x.DATASET_NAME
      AND a.OBJECT_TYPE = 'D' AND PPD.POWERBI_OBJECT_TYPE = 'T'
      AND a.ACTION_TYPE = 'P' AND x.ACTION_TYPE = 'P'
      AND NVL(a.APPLY_POLICY,'') = NVL(x.APPLY_POLICY,'')
      AND NVL(a.POLICY_EFFECTIVE_DATE,'1900-01-01') = NVL(x.POLICY_EFFECTIVE_DATE,'1900-01-01')
  )
  /*
      No dataset action the same or newer runlog
  */
  AND NOT EXISTS 
  (
      SELECT 1
      FROM METADATA.POWERBI_ACTION r
          , LATERAL flatten (INPUT => r.PUBLISH_INFO:COBS) inf
          , LATERAL flatten (INPUT => inf.VALUE:PUBLISH_INFO[0]) res
      WHERE
      r.DATASET_NAME = x.DATASET_NAME
      AND r.OBJECT_TYPE = 'D' AND PPD.POWERBI_OBJECT_TYPE = 'T'
      AND r.ACTION_TYPE = 'P' AND x.ACTION_TYPE = 'P'
      AND NVL(r.APPLY_POLICY,'') = NVL(x.APPLY_POLICY,'')
      AND NVL(r.POLICY_EFFECTIVE_DATE,'1900-01-01') = NVL(x.POLICY_EFFECTIVE_DATE,'1900-01-01')
      AND inf.VALUE:COBID::NUMERIC = PPD.COBID
      AND res.PATH = ppd.PUBLISH_TYPE
      AND to_timestamp_tz(res.VALUE::varchar) >= ppd.MAX_INSERT_TIME
  )
)
SELECT 	WORKSPACE_NAME,
	DATASET_NAME,
	OBJECT_NAME,
	OBJECT_TYPE,
	ACTION_TYPE,
	PARTITION_TYPE,
	APPLY_POLICY,
	POLICY_EFFECTIVE_DATE,
	ORIGINAL_COBID,
	COBID,
	INSERT_SOURCE,
	MAX_RUN_LOG_ID,
	MAX_RUN_LOG_TIME,
	PUBLISH_INFO
FROM raw_sql
WHERE SEQ_ID = 1;