create or replace view DVLP_RAPTOR_NEWADJ.STAGING.IDM_VAR_UPLOAD_STREAM_DATA_MERGE(
	COBID,
	PROCESS_TYPE,
	ADJUSTMENT_TYPE,
	ENTITY_CODE,
	SOURCE_SYSTEM_CODE,
	BOOK_CODE,
	CURRENCY_CODE,
	SCENARIO_DATE_ID,
	TRADE_CODE,
	VAR_SUB_COMPONENT_NAME,
	VAR_SUB_COMPONENT_ID,
	ADJUSTMENT_VALUE_IN_USD,
	DML_TYPE,
	FILE_NAME,
	CATEGORY,
	DETAIL,
	GLOBAL_REFERENCE,
	RUN_STATUS,
	DEPARTMENT_CODE
) as
-- VIEW TO GET THE VALUES THAT CAME AS NULL IN THE UNPIVOT PROCESS
SELECT 
	SD.COBID, 
	SD.PROCESS_TYPE, 
	SD.ADJUSTMENT_TYPE, 
	SD.ENTITY_CODE, 
	SD.SOURCE_SYSTEM_CODE, 
	SD.BOOK_CODE, 
	SD.CURRENCY_CODE, 
	SD.SCENARIO_DATE_ID, 
	SD.TRADE_CODE, 
	SD.VAR_SUB_COMPONENT_NAME, 
	SD.VAR_SUB_COMPONENT_ID, 
	SD.ADJUSTMENT_VALUE_IN_USD, 
	SD.DML_TYPE, 
	SD.FILE_NAME,  
	SD.CATEGORY,
	SD.DETAIL,
	SD.GLOBAL_REFERENCE,
    CASE WHEN PVSO.PUBLISH_STATUS IS NULL THEN 'Pending' 
                    WHEN SD.TENDAY = 'Y' THEN 'Pending'
                    ELSE 'Rejected - SignedOff' END AS RUN_STATUS,
	SD.DEPARTMENT_CODE
FROM STAGING.IDM_VAR_UPLOAD_STREAM_DATA SD
LEFT JOIN BATCH.PUBLISH_VAR_SIGNOFF_STATUS PVSO 
	 ON SD.COBID = PVSO.COBID 
	AND SD.ENTITY_CODE = PVSO.ENTITY_CODE
	AND SD.PROCESS_TYPE = 'VAR'
	AND PVSO.PUBLISH_STATUS = 'SignedOff'
UNION ALL
SELECT
	tb.COBID, 
	tb.PROCESS_TYPE, 
	tb.ADJUSTMENT_TYPE, 
	tb.ENTITY_CODE, 
	tb.SOURCE_SYSTEM_CODE, 
	tb.BOOK_CODE, 
	tb.CURRENCY_CODE, 
	tb.SCENARIO_DATE_ID, 
	tb.TRADE_CODE, 
	NULL, 
	tb.VAR_SUB_COMPONENT_ID, 
	tb.ADJUSTMENT_VALUE_IN_USD, 
	'D' DML_TYPE, 
	tb.FILE_NAME, 
	tb.CATEGORY,
	tb.DETAIL,
	tb.GLOBAL_REFERENCE,
    CASE WHEN PVSO.PUBLISH_STATUS IS NULL THEN 'Pending' 
                    WHEN vsc.VAR_SUB_COMPONENT_DAY_TYPE = 10 THEN 'Pending'
                    ELSE 'Rejected - SignedOff' END AS RUN_STATUS,
	tb.DEPARTMENT_CODE
FROM ADJUSTMENT.IDM_VAR_UPLOAD tb
LEFT JOIN BATCH.PUBLISH_VAR_SIGNOFF_STATUS PVSO 
	 ON tb.COBID = PVSO.COBID 
	AND tb.ENTITY_CODE = PVSO.ENTITY_CODE
	AND tb.PROCESS_TYPE = 'VAR'
	AND PVSO.PUBLISH_STATUS = 'SignedOff'
LEFT JOIN DIMENSION.VAR_SUB_COMPONENT vsc
    ON tb.VAR_SUB_COMPONENT_ID = vsc.VAR_SUB_COMPONENT_ID
WHERE NOT EXISTS (
	SELECT 1 FROM STAGING.IDM_VAR_UPLOAD_STREAM_DATA vw 
	WHERE IFNULL(vw.COBID,0)=IFNULL(tb.COBID,0)
	  AND IFNULL(vw.ENTITY_CODE,'')=IFNULL(tb.ENTITY_CODE,'')
	  AND IFNULL(vw.VAR_SUB_COMPONENT_ID,0)=IFNULL(tb.VAR_SUB_COMPONENT_ID,0)
	  AND IFNULL(vw.FILE_NAME,'')=IFNULL(tb.FILE_NAME,'')
	  AND IFNULL(vw.SCENARIO_DATE_ID,0)=IFNULL(tb.SCENARIO_DATE_ID,0)
	  AND IFNULL(vw.SOURCE_SYSTEM_CODE,'')=IFNULL(tb.SOURCE_SYSTEM_CODE,'')
	  AND IFNULL(vw.BOOK_CODE,'')=IFNULL(tb.BOOK_CODE,'')
	  AND IFNULL(vw.CURRENCY_CODE,'')=IFNULL(tb.CURRENCY_CODE,'')
	  AND IFNULL(vw.TRADE_CODE,'')=IFNULL(tb.TRADE_CODE,'')
	  AND IFNULL(vw.DEPARTMENT_CODE,'')=IFNULL(tb.DEPARTMENT_CODE,'')
  	)
  AND FILE_NAME IN (SELECT DISTINCT FILE_NAME FROM STAGING.IDM_VAR_UPLOAD_STREAM_DATA);