create or replace view DVLP_RAPTOR_NEWADJ.STAGING.IDM_VAR_UPLOAD_STREAM_DATA(
	COBID,
	PROCESS_TYPE,
	ADJUSTMENT_TYPE,
	ENTITY_CODE,
	SOURCE_SYSTEM_CODE,
	BOOK_CODE,
	CURRENCY_CODE,
	SCENARIO_DATE_ID,
	TRADE_CODE,
	VAR_SUB_COMPONENT_NAME,
	VAR_SUB_COMPONENT_ID,
	ADJUSTMENT_VALUE_IN_USD,
	DML_TYPE,
	FILE_NAME,
	CATEGORY,
	DETAIL,
	GLOBAL_REFERENCE,
	TENDAY,
	DEPARTMENT_CODE
) as
WITH VALID_FILE_STREAM AS (
SELECT * 
FROM STAGING.IDM_VAR_UPLOAD_STREAM A
WHERE NOT EXISTS (SELECT 1 FROM STAGING.IDM_VAR_UPLOAD B WHERE COBID IS NULL AND A.RAVEN_FILENAME = B.RAVEN_FILENAME)
)
SELECT 
    COBID,
	PROCESS_TYPE,
	ADJUSTMENT_TYPE,
	ENTITY_CODE,
	SOURCE_SYSTEM_CODE,
	BOOK_CODE,
	CURRENCY_CODE,
	SCENARIO_DATE_ID,
	TRADE_CODE,
	VAR_SUB_COMPONENT_NAME,
	VAR_SUB_COMPONENT_ID,
	ADJUSTMENT_VALUE_IN_USD,
	DML_TYPE,
	FILE_NAME,
	CATEGORY,
	DETAIL,
	GLOBAL_REFERENCE, TENDAY,
	DEPARTMENT_CODE
FROM 
(
	SELECT 
		A.COBID,
		'VAR' AS PROCESS_TYPE,
		'Upload' AS ADJUSTMENT_TYPE,
		A.ENTITY_CODE, 
		A.SOURCE_SYSTEM_CODE, 
		A.BOOK_CODE, 
		A.CURRENCY_CODE, 
		A.SCENARIO_DATE AS SCENARIO_DATE_ID,
		A.TRADE_CODE,
		A.VAR_SUB_COMPONENT_NAME,
		SC.VAR_SUB_COMPONENT_ID,
		ADJUSTMENT_VALUE_IN_USD,
		A.DML_TYPE,
		A.RAVEN_FILENAME AS FILE_NAME,
		A.CATEGORY,
		A.DETAIL,
		UPPER( SHA1(A.COBID||A.ENTITY_CODE||A.RAVEN_FILENAME) ) AS GLOBAL_REFERENCE,
		A.TENDAY,
		A.DEPARTMENT_CODE
	FROM (
		-- This subquery figures out what to do when data is deleted from the SOURCE (SQL Server table: GLOBAL.StagingAdjustmentSnowflake)
		-- A deletion from the SOURCE table results in an update to the DIMENSION.ADJUSTMENT table
		SELECT DL.*,  'D' AS DML_TYPE
		FROM (
		SELECT 
		COBID,ENTITY_CODE,SOURCE_SYSTEM_CODE,BOOK_CODE,CURRENCY_CODE,SCENARIO_DATE,TRADE_CODE,ALL_VAR,ALL_VAR_SKEW,BASIS_VAR,BOND_ASSET_SPREAD_VAR,CROSS_EFFECTS,EQUITY_PRICE_VAR,EQUITY_VEGA_VAR,FX_RATE_VAR,FX_VOLATILITY_VAR,INFLATION_RATE_CURVE_VAR,INFLATION_VOL_VAR,INTEREST_RATE_CURVE_VAR,INTEREST_RATE_VEGA_VAR,IR_CAP_VOL_VAR,IR_CAP_VOL_VAR_SKEW,IR_SKEW_VOL_VAR,IR_SWAPTION_VOL_VAR,IR_SWAPTION_VOL_VAR_SKEW,MTG_SPRD_VAR,OAS_VAR,PAR_CREDIT_SPREAD_VAR,RAVEN_FILENAME,CATEGORY,DETAIL,TENDAY,DEPARTMENT_CODE
		FROM VALID_FILE_STREAM S
		WHERE METADATA$ACTION = 'DELETE'
		AND METADATA$ISUPDATE = 'FALSE'
		AND NOT EXISTS (SELECT 1 
						  FROM VALID_FILE_STREAM SD 
						 WHERE METADATA$ACTION = 'INSERT' 
						 AND METADATA$ISUPDATE = 'FALSE'
						 AND S.COBID = SD.COBID
						 AND equal_null(S.ENTITY_CODE,SD.ENTITY_CODE)
						 AND equal_null(S.SOURCE_SYSTEM_CODE,SD.SOURCE_SYSTEM_CODE)
						 AND equal_null(S.BOOK_CODE, SD.BOOK_CODE)
						 AND equal_null(S.CURRENCY_CODE,SD.CURRENCY_CODE)
						 AND equal_null(S.SCENARIO_DATE,SD.SCENARIO_DATE)
						 AND equal_null(S.TRADE_CODE,SD.TRADE_CODE)
						 AND equal_null(S.RAVEN_FILENAME,SD.RAVEN_FILENAME)
						 AND equal_null(S.DEPARTMENT_CODE,SD.DEPARTMENT_CODE)
					)
		) DL
		UNION ALL
		-- This subquery figures out what to do when data is inserted into the SOURCE table
		-- An insert to the SOURCE table results in an INSERT to the DIMENSION.ADJUSTMENT table
		SELECT I.*,  'I' AS DML_TYPE
		FROM (
		SELECT 
		COBID,ENTITY_CODE,SOURCE_SYSTEM_CODE,BOOK_CODE,CURRENCY_CODE,SCENARIO_DATE,TRADE_CODE,ALL_VAR,ALL_VAR_SKEW,BASIS_VAR,BOND_ASSET_SPREAD_VAR,CROSS_EFFECTS,EQUITY_PRICE_VAR,EQUITY_VEGA_VAR,FX_RATE_VAR,FX_VOLATILITY_VAR,INFLATION_RATE_CURVE_VAR,INFLATION_VOL_VAR,INTEREST_RATE_CURVE_VAR,INTEREST_RATE_VEGA_VAR,IR_CAP_VOL_VAR,IR_CAP_VOL_VAR_SKEW,IR_SKEW_VOL_VAR,IR_SWAPTION_VOL_VAR,IR_SWAPTION_VOL_VAR_SKEW,MTG_SPRD_VAR,OAS_VAR,PAR_CREDIT_SPREAD_VAR,RAVEN_FILENAME,CATEGORY,DETAIL,TENDAY,DEPARTMENT_CODE
		FROM VALID_FILE_STREAM I
		WHERE METADATA$ACTION = 'INSERT'
		AND METADATA$ISUPDATE = 'FALSE'
		AND NOT EXISTS (SELECT 1 
						  FROM VALID_FILE_STREAM ID 
						 WHERE METADATA$ACTION = 'DELETE' 
						   AND METADATA$ISUPDATE = 'FALSE'
						   AND I.COBID = ID.COBID
						   AND equal_null(I.ENTITY_CODE,ID.ENTITY_CODE)
						   AND equal_null(I.SOURCE_SYSTEM_CODE,ID.SOURCE_SYSTEM_CODE)
						   AND equal_null(I.BOOK_CODE, ID.BOOK_CODE)
						   AND equal_null(I.CURRENCY_CODE,ID.CURRENCY_CODE)
						   AND equal_null(I.SCENARIO_DATE,ID.SCENARIO_DATE)
						   AND equal_null(I.TRADE_CODE,ID.TRADE_CODE)
						   AND equal_null(I.RAVEN_FILENAME,ID.RAVEN_FILENAME)
						   AND equal_null(I.DEPARTMENT_CODE,ID.DEPARTMENT_CODE)
					   )
		) I
		UNION ALL
		-- This subquery figures out what to do when data is updated in the SOURCE table
		-- An update to the SOURCE table results in an update AND the DIMENSION.ADJUSTMENT table with RUN_STATUS = 'Pending'
		SELECT U.*,  'U' AS DML_TYPE
		FROM (
		SELECT 
		COBID,ENTITY_CODE,SOURCE_SYSTEM_CODE,BOOK_CODE,CURRENCY_CODE,SCENARIO_DATE,TRADE_CODE,ALL_VAR,ALL_VAR_SKEW,BASIS_VAR,BOND_ASSET_SPREAD_VAR,CROSS_EFFECTS,EQUITY_PRICE_VAR,EQUITY_VEGA_VAR,FX_RATE_VAR,FX_VOLATILITY_VAR,INFLATION_RATE_CURVE_VAR,INFLATION_VOL_VAR,INTEREST_RATE_CURVE_VAR,INTEREST_RATE_VEGA_VAR,IR_CAP_VOL_VAR,IR_CAP_VOL_VAR_SKEW,IR_SKEW_VOL_VAR,IR_SWAPTION_VOL_VAR,IR_SWAPTION_VOL_VAR_SKEW,MTG_SPRD_VAR,OAS_VAR,PAR_CREDIT_SPREAD_VAR,RAVEN_FILENAME,CATEGORY,DETAIL,TENDAY,DEPARTMENT_CODE
		FROM VALID_FILE_STREAM UI
		WHERE METADATA$ACTION = 'INSERT'
		AND METADATA$ISUPDATE = 'FALSE'
		AND EXISTS (SELECT 1 
					  FROM VALID_FILE_STREAM ID 
					 WHERE METADATA$ACTION = 'DELETE' 
					   AND METADATA$ISUPDATE = 'FALSE'
					   AND UI.COBID = ID.COBID
					   AND equal_null(UI.ENTITY_CODE,ID.ENTITY_CODE)
					   AND equal_null(UI.SOURCE_SYSTEM_CODE,ID.SOURCE_SYSTEM_CODE)
					   AND equal_null(UI.BOOK_CODE, ID.BOOK_CODE)
					   AND equal_null(UI.CURRENCY_CODE,ID.CURRENCY_CODE)
					   AND equal_null(UI.SCENARIO_DATE,ID.SCENARIO_DATE)
					   AND equal_null(UI.TRADE_CODE,ID.TRADE_CODE)
					   AND equal_null(UI.RAVEN_FILENAME,ID.RAVEN_FILENAME)
					   AND equal_null(UI.DEPARTMENT_CODE,ID.DEPARTMENT_CODE)
				)
		EXCEPT
		SELECT 
		COBID,ENTITY_CODE,SOURCE_SYSTEM_CODE,BOOK_CODE,CURRENCY_CODE,SCENARIO_DATE,TRADE_CODE,ALL_VAR,ALL_VAR_SKEW,BASIS_VAR,BOND_ASSET_SPREAD_VAR,CROSS_EFFECTS,EQUITY_PRICE_VAR,EQUITY_VEGA_VAR,FX_RATE_VAR,FX_VOLATILITY_VAR,INFLATION_RATE_CURVE_VAR,INFLATION_VOL_VAR,INTEREST_RATE_CURVE_VAR,INTEREST_RATE_VEGA_VAR,IR_CAP_VOL_VAR,IR_CAP_VOL_VAR_SKEW,IR_SKEW_VOL_VAR,IR_SWAPTION_VOL_VAR,IR_SWAPTION_VOL_VAR_SKEW,MTG_SPRD_VAR,OAS_VAR,PAR_CREDIT_SPREAD_VAR,RAVEN_FILENAME,CATEGORY,DETAIL,TENDAY,DEPARTMENT_CODE
		FROM VALID_FILE_STREAM
		WHERE METADATA$ACTION = 'DELETE'
		AND METADATA$ISUPDATE = 'FALSE'
		) U
		) A
		UNPIVOT(
			ADJUSTMENT_VALUE_IN_USD FOR VAR_SUB_COMPONENT_NAME 
				IN (
					ALL_VAR, ALL_VAR_SKEW, BASIS_VAR, BOND_ASSET_SPREAD_VAR, 
					CROSS_EFFECTS, EQUITY_PRICE_VAR, EQUITY_VEGA_VAR, FX_RATE_VAR, 
					FX_VOLATILITY_VAR, INFLATION_RATE_CURVE_VAR, INFLATION_VOL_VAR, 
					INTEREST_RATE_CURVE_VAR, INTEREST_RATE_VEGA_VAR, IR_CAP_VOL_VAR, 
					IR_CAP_VOL_VAR_SKEW, IR_SKEW_VOL_VAR, IR_SWAPTION_VOL_VAR, 
					IR_SWAPTION_VOL_VAR_SKEW, MTG_SPRD_VAR, OAS_VAR, PAR_CREDIT_SPREAD_VAR
				))
		LEFT JOIN DIMENSION.VAR_SUB_COMPONENT SC ON UPPER(SC.VAR_SUB_COMPONENT_NAME)  
			= CASE  
				WHEN A.TENDAY='Y' THEN
					CASE 
						WHEN A.VAR_SUB_COMPONENT_NAME = 'INFLATION_RATE_CURVE_VAR' THEN 'Inflation VaR (10 Day)'
                        WHEN A.VAR_SUB_COMPONENT_NAME = 'EQUITY_PRICE_VAR' THEN 'Equity Price (10 Day)'
                        WHEN A.VAR_SUB_COMPONENT_NAME = 'PAR_CREDIT_SPREAD_VAR' THEN 'Par Credit Spread VAR (10 Day)'
						ELSE CONCAT(UPPER(REPLACE(A.VAR_SUB_COMPONENT_NAME,'_',' ')), ' (10 Day)')
					END
				ELSE CONCAT(UPPER(REPLACE(A.VAR_SUB_COMPONENT_NAME,'_',' ')))
			END					
);