create or replace view DVLP_RAPTOR_NEWADJ.STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM_DATA(
	COBID,
	ADJUSTMENT_ID,
	SOURCE_COBID,
	APPROVAL_ID,
	ADJUSTMENT_TYPE,
	REASON,
	FORM_DATA,
	ADJUSTED_BY,
	ADJUSTMENT_CREATED,
	ADJUSTMENT_COMPLETED,
	STATUS,
	ENTITY_CODE,
	ENTITY_KEY,
	DEPARTMENT_CODE,
	IS_DELETED,
	DELETED_BY,
	ADJUSTMENT_DELETED,
	TEMP_ID,
	DML_TYPE
) as
-- This subquery figures out what to do when data is deleted from the SOURCE (SQL Server table: GLOBAL.StagingAdjustmentSnowflake)
-- A deletion from the SOURCE table results in an update to the DIMENSION.ADJUSTMENT table
SELECT DL.*,  'D' AS 
DML_TYPE
FROM (
SELECT 
COBID, ADJUSTMENT_ID, SOURCE_COBID, APPROVAL_ID, ADJUSTMENT_TYPE, REASON, FORM_DATA, ADJUSTED_BY, ADJUSTMENT_CREATED, ADJUSTMENT_COMPLETED, STATUS, ENTITY_CODE, ENTITY_KEY, DEPARTMENT_CODE, IS_DELETED, DELETED_BY, ADJUSTMENT_DELETED, TEMP_ID
FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM S
WHERE METADATA$ACTION = 'DELETE'
AND METADATA$ISUPDATE = 'FALSE'
AND NOT EXISTS (SELECT 1 FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM SD WHERE METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'FALSE' AND S.ADJUSTMENT_ID = SD.ADJUSTMENT_ID)
) DL
UNION ALL
-- This subquery figures out what to do when data is inserted into the SOURCE table
-- An insert to the SOURCE table results in an INSERT to the DIMENSION.ADJUSTMENT table
SELECT I.*,  'I' AS 
DML_TYPE
FROM (
SELECT 
COBID, ADJUSTMENT_ID, SOURCE_COBID, APPROVAL_ID, ADJUSTMENT_TYPE, REASON, FORM_DATA, ADJUSTED_BY, ADJUSTMENT_CREATED, ADJUSTMENT_COMPLETED, STATUS, ENTITY_CODE, ENTITY_KEY, DEPARTMENT_CODE, IS_DELETED, DELETED_BY, ADJUSTMENT_DELETED, TEMP_ID
FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM I
WHERE METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = 'FALSE'
AND NOT EXISTS (SELECT 1 FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM ID WHERE METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = 'FALSE' AND I.ADJUSTMENT_ID = ID.ADJUSTMENT_ID)
) I
UNION ALL
-- This subquery figures out what to do when data is updated in the SOURCE table
-- An update to the SOURCE table results in an update AND the DIMENSION.ADJUSTMENT table with RUN_STATUS = 'Pending'
SELECT U.*,  'U' AS 
DML_TYPE
FROM (
SELECT 
COBID, ADJUSTMENT_ID, SOURCE_COBID, APPROVAL_ID, ADJUSTMENT_TYPE, REASON, FORM_DATA, ADJUSTED_BY, ADJUSTMENT_CREATED, ADJUSTMENT_COMPLETED, STATUS, ENTITY_CODE, ENTITY_KEY, DEPARTMENT_CODE, IS_DELETED, DELETED_BY, ADJUSTMENT_DELETED, TEMP_ID
FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM UI
WHERE METADATA$ACTION = 'INSERT'
AND METADATA$ISUPDATE = 'FALSE'
AND EXISTS (SELECT 1 FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM UD WHERE UD.METADATA$ACTION = 'DELETE' AND UD.METADATA$ISUPDATE = 'FALSE' AND UI.ADJUSTMENT_ID = UD.ADJUSTMENT_ID)
EXCEPT
SELECT 
COBID, ADJUSTMENT_ID, SOURCE_COBID, APPROVAL_ID, ADJUSTMENT_TYPE, REASON, FORM_DATA, ADJUSTED_BY, ADJUSTMENT_CREATED, ADJUSTMENT_COMPLETED, STATUS, ENTITY_CODE, ENTITY_KEY, DEPARTMENT_CODE, IS_DELETED, DELETED_BY, ADJUSTMENT_DELETED, TEMP_ID
FROM STAGING.IDM_GLOBAL_ADJUSTMENT_SF_STREAM
WHERE METADATA$ACTION = 'DELETE'
AND METADATA$ISUPDATE = 'FALSE'
) U;