-- =============================================================================
-- 07_SECURITY_GOVERNANCE.SQL
-- RBAC roles, Row Access Policies, Object Tagging, Masking
-- =============================================================================

USE DATABASE ADJUSTMENT_DB;
USE WAREHOUSE ADJUSTMENT_WH;

-- ═════════════════════════════════════════════════════════════════════════════
-- 1. CUSTOM ROLES HIERARCHY
--
--    SYSADMIN
--       └── ADJ_ADMIN          (manage config, override anything)
--            ├── ADJ_APPROVER   (approve/reject adjustments)
--            └── ADJ_OPERATOR   (create/submit adjustments)
--                 └── ADJ_VIEWER (read-only visibility)
-- ═════════════════════════════════════════════════════════════════════════════

CREATE ROLE IF NOT EXISTS ADJ_ADMIN;
CREATE ROLE IF NOT EXISTS ADJ_APPROVER;
CREATE ROLE IF NOT EXISTS ADJ_OPERATOR;
CREATE ROLE IF NOT EXISTS ADJ_VIEWER;

-- Hierarchy
GRANT ROLE ADJ_VIEWER   TO ROLE ADJ_OPERATOR;
GRANT ROLE ADJ_OPERATOR  TO ROLE ADJ_APPROVER;
GRANT ROLE ADJ_APPROVER  TO ROLE ADJ_ADMIN;
GRANT ROLE ADJ_ADMIN     TO ROLE SYSADMIN;

-- ─── Database & Schema Grants ────────────────────────────────────────────────
GRANT USAGE ON DATABASE ADJUSTMENT_DB TO ROLE ADJ_VIEWER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ADJUSTMENT_DB TO ROLE ADJ_VIEWER;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE ADJUSTMENT_WH TO ROLE ADJ_VIEWER;
GRANT USAGE ON WAREHOUSE ADJUSTMENT_WH TO ROLE ADJ_OPERATOR;
GRANT USAGE ON WAREHOUSE ADJUSTMENT_WH TO ROLE ADJ_APPROVER;
GRANT USAGE ON WAREHOUSE ADJUSTMENT_WH TO ROLE ADJ_ADMIN;

-- ─── ADJ_VIEWER: Read-only on all tables and dynamic tables ──────────────────
GRANT SELECT ON ALL TABLES IN SCHEMA FACT TO ROLE ADJ_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE ADJ_VIEWER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA MART TO ROLE ADJ_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA AI TO ROLE ADJ_VIEWER;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA FACT TO ROLE ADJ_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CORE TO ROLE ADJ_VIEWER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA MART TO ROLE ADJ_VIEWER;

-- ─── ADJ_OPERATOR: Create adjustments (INSERT on header + line items) ────────
GRANT INSERT ON TABLE CORE.ADJ_HEADER TO ROLE ADJ_OPERATOR;
GRANT INSERT ON TABLE CORE.ADJ_LINE_ITEM TO ROLE ADJ_OPERATOR;
GRANT INSERT ON TABLE CORE.ADJ_STATUS_HISTORY TO ROLE ADJ_OPERATOR;

-- Allow calling stored procedures
GRANT USAGE ON PROCEDURE CORE.SP_PREVIEW_ADJUSTMENT(VARCHAR, VARIANT, DATE, FLOAT, DATE) TO ROLE ADJ_OPERATOR;
GRANT USAGE ON PROCEDURE CORE.SP_CREATE_ADJUSTMENT(VARCHAR, VARIANT, DATE, FLOAT, DATE, VARCHAR, VARCHAR) TO ROLE ADJ_OPERATOR;

-- ─── ADJ_APPROVER: Approve/reject + apply adjustments ───────────────────────
GRANT UPDATE ON TABLE CORE.ADJ_HEADER TO ROLE ADJ_APPROVER;
GRANT USAGE ON PROCEDURE CORE.SP_UPDATE_ADJUSTMENT_STATUS(NUMBER, VARCHAR, VARCHAR) TO ROLE ADJ_APPROVER;
GRANT USAGE ON PROCEDURE CORE.SP_REVERSE_ADJUSTMENT(NUMBER, VARCHAR) TO ROLE ADJ_APPROVER;

-- ─── ADJ_ADMIN: Full control ─────────────────────────────────────────────────
GRANT ALL ON DATABASE ADJUSTMENT_DB TO ROLE ADJ_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE ADJUSTMENT_DB TO ROLE ADJ_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA CORE TO ROLE ADJ_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA FACT TO ROLE ADJ_ADMIN;


-- ═════════════════════════════════════════════════════════════════════════════
-- 2. ROW ACCESS POLICY
--    Restricts which adjustments a user can see based on entity_key.
--    Useful if different teams manage different entities.
-- ═════════════════════════════════════════════════════════════════════════════

-- Mapping table: which users can see which entities
CREATE TABLE IF NOT EXISTS CORE.USER_ENTITY_ACCESS (
    USER_NAME   VARCHAR(256)    NOT NULL,
    ENTITY_KEY  VARCHAR(50)     NOT NULL,
    CONSTRAINT PK_UEA PRIMARY KEY (USER_NAME, ENTITY_KEY)
)
COMMENT = 'Maps users to the entities they are authorized to view/adjust';

-- Row access policy
CREATE OR REPLACE ROW ACCESS POLICY CORE.RAP_ENTITY_ACCESS
AS (entity_key VARCHAR) RETURNS BOOLEAN ->
    -- ADJ_ADMIN bypasses
    IS_ROLE_IN_SESSION('ADJ_ADMIN')
    OR
    -- Check entity access mapping
    entity_key IN (
        SELECT ea.ENTITY_KEY
        FROM CORE.USER_ENTITY_ACCESS ea
        WHERE ea.USER_NAME = CURRENT_USER()
    )
;

-- Apply to tables (uncomment to activate):
-- ALTER TABLE CORE.ADJ_LINE_ITEM ADD ROW ACCESS POLICY CORE.RAP_ENTITY_ACCESS ON (ENTITY_KEY);
-- ALTER TABLE FACT.FACT_TABLE ADD ROW ACCESS POLICY CORE.RAP_ENTITY_ACCESS ON (ENTITY_KEY);
-- ALTER DYNAMIC TABLE MART.FACT_ADJUSTED ADD ROW ACCESS POLICY CORE.RAP_ENTITY_ACCESS ON (ENTITY_KEY);


-- ═════════════════════════════════════════════════════════════════════════════
-- 3. OBJECT TAGGING (Data Governance & Lineage)
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TAG IF NOT EXISTS CORE.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PII', 'CONFIDENTIAL', 'INTERNAL', 'PUBLIC'
    COMMENT = 'Data classification tag for governance';

CREATE TAG IF NOT EXISTS CORE.DATA_DOMAIN
    ALLOWED_VALUES 'ADJUSTMENT', 'FACT', 'AUDIT', 'CONFIG'
    COMMENT = 'Business domain tag';

CREATE TAG IF NOT EXISTS CORE.DATA_OWNER
    COMMENT = 'Team or individual responsible for the data';

-- Apply tags
ALTER TABLE CORE.ADJ_HEADER SET TAG
    CORE.DATA_CLASSIFICATION = 'CONFIDENTIAL',
    CORE.DATA_DOMAIN = 'ADJUSTMENT';

ALTER TABLE CORE.ADJ_LINE_ITEM SET TAG
    CORE.DATA_CLASSIFICATION = 'CONFIDENTIAL',
    CORE.DATA_DOMAIN = 'ADJUSTMENT';

ALTER TABLE FACT.FACT_TABLE SET TAG
    CORE.DATA_CLASSIFICATION = 'CONFIDENTIAL',
    CORE.DATA_DOMAIN = 'FACT';

ALTER TABLE CORE.ADJ_STATUS_HISTORY SET TAG
    CORE.DATA_CLASSIFICATION = 'INTERNAL',
    CORE.DATA_DOMAIN = 'AUDIT';

ALTER DYNAMIC TABLE MART.FACT_ADJUSTED SET TAG
    CORE.DATA_CLASSIFICATION = 'CONFIDENTIAL',
    CORE.DATA_DOMAIN = 'FACT';


-- ═════════════════════════════════════════════════════════════════════════════
-- 4. COLUMN-LEVEL MASKING POLICY (optional: mask CREATED_BY for viewers)
-- ═════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE MASKING POLICY CORE.MASK_USERNAME AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN IS_ROLE_IN_SESSION('ADJ_APPROVER') OR IS_ROLE_IN_SESSION('ADJ_ADMIN')
        THEN val
        ELSE '***MASKED***'
    END;

-- Apply to columns (uncomment to activate):
-- ALTER TABLE CORE.ADJ_HEADER MODIFY COLUMN CREATED_BY SET MASKING POLICY CORE.MASK_USERNAME;
-- ALTER TABLE CORE.ADJ_STATUS_HISTORY MODIFY COLUMN CHANGED_BY SET MASKING POLICY CORE.MASK_USERNAME;
