USE SCHEMA ADJUSTMENT;
create or replace view VW_ADJUSTMENTS_DIRECT_SBM as
with base as (
	select
		adr.*
	from ADJUSTMENT.ADJUSTMENTS_DIRECT_SBM adr
),
enriched as (
	select
		base.*,
		'DIRECT-SBM' as LOAD_SET,
		'NonCVA' as LOAD_SOURCE,
		CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9) as LOAD_TIMESTAMP,
		COALESCE(NULLIF(base.CCY1, ''), base.CCY_AMT) as CURRENCY_CODE,
		IFF(LEN(CONCAT(base.CCY2, '-', base.CCY1)) < 7, null, CONCAT(base.CCY2, '-', base.CCY1)) as CURRENCY_PAIR_CODE,
		MD5(
			COALESCE(CAST(base.DIRECT_SBM_FILENAME AS VARCHAR), '_dbt_utils_surrogate_key_null_')
			|| '-'
			|| COALESCE(CAST(base.DIRECT_SBM_FILE_ROW_NUMBER AS VARCHAR), '_dbt_utils_surrogate_key_null_')
			|| '-'
			|| COALESCE(CAST(base.DIRECT_SBM_STAGE_TIMESTAMP AS VARCHAR), '_dbt_utils_surrogate_key_null_')
			|| '-'
			|| COALESCE(CAST(base.DIRECT_SBM_DATASET_NAME AS VARCHAR), '_dbt_utils_surrogate_key_null_')
		) as FRTBSA_SENSITIVITY_KEY
	from base
)
select
	enriched.*, 
	COALESCE(td.TRADE_SOURCE_SYSTEM_CODE, 'MS') as SOURCE_SYSTEM_CODE,
	COALESCE(td.BOOK_CODE, b.BOOK_CODE) as BOOK_CODE,
	COALESCE(td.BOOK_CODE, b.BOOK_CODE) as BOOK_CODE_SABRE,
	COALESCE(b.BOOK_KEY, -1) as BOOK_KEY,
	enriched.ENTITY_CODE as ENTITY_CODE_SABRE,
	IFF(COALESCE(enriched.CURVE_TYPE, '') = '', 'N/A', enriched.CURVE_TYPE) as CURVE_CODE,
	COALESCE(cc.CURVE_CURRENCY_KEY, -1) as CURVE_CURRENCY_KEY,
	COALESCE(cp.CURRENCY_PAIR_KEY, -1) as CURRENCY_PAIR_KEY,
	CASE enriched.GUARANTEED_TYPE WHEN 'YES' THEN UPPER(enriched.ENTITY_CODE) ELSE 'N/A' END as GUARANTEED_ENTITY,
	COALESCE(fi.FRTB_INSTRUMENT_KEY, -1) as FRTB_INSTRUMENT_KEY,
	COALESCE(ci.INSTRUMENT_CODE, ci2.INSTRUMENT_CODE, 'N/A')::VARCHAR(100) COLLATE 'en-ci' as INSTRUMENT_CODE,
	TRUE as IS_BELOW_THE_LINE_TYPOLOGY,
	TRUE as IS_FRTB_STATUS_ACTIVE,
        COALESCE(mt.MEASURE_TYPE_KEY, -1) as MEASURE_TYPE_KEY,
        COALESCE(NULLIF(td.MUREX_INSTRUMENT, ''), 'N/A') as MUREX_INSTRUMENT,
        td.MUREX_VERSION as MUREX_VERSION,
        COALESCE(td.PRODUCT_CATEGORY_ATTRIBUTES_KEY, -1) as PRODUCT_CATEGORY_ATTRIBUTES_KEY,
        5 as RAPTOR_LOGIC_TEMPLATE_KEY,
        CASE
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) IN ('MUSI', 'MUSEU') THEN 'LONDON'
            ELSE 'NEW YORK'
        END as REGION_DATA_SET_CODE,
        CASE
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSI' THEN enriched.PRA_BUCKET
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSEU' THEN enriched.EBA_BUCKET
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSUSA' THEN enriched.FED_BUCKET
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSCAN' THEN enriched.BUCKET
            ELSE NULL
        END as REGULATOR_BUCKET,
        CASE
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSI' THEN enriched.PRA_BUCKET_NAME
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSEU' THEN enriched.EBA_BUCKET_NAME
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSUSA' THEN enriched.FED_BUCKET_NAME
			WHEN UPPER(COALESCE(enriched.ENTITY_CODE, '')) = 'MUSCAN' THEN NULL
            ELSE NULL
        END as REGULATOR_BUCKET_NAME,
FALSE as IS_CVA_MEASURE_TYPE,
	IFF(enriched.MEASURE_TYPE_CODE IN ('FRTBEQSPOTDELTA', 'FRTBEQREPODELTA'), TRUE, FALSE) as IS_DUPLICATE_MEASURE_TYPE,
	TRUE as IS_OFFICIAL_SOURCE,
	FALSE as IS_CVA_COUNTERPARTY,
	TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') as EVALUATION_DATE,
	CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9) as ADJUSTMENT_CREATED_TIMESTAMP,
	COALESCE(fci.COMMON_INSTRUMENT_FCD_KEY, fci2.COMMON_INSTRUMENT_FCD_KEY, -1) as COMMON_INSTRUMENT_FCD_KEY,
	COALESCE(ci.COMMON_INSTRUMENT_KEY, ci2.COMMON_INSTRUMENT_KEY, -1) as COMMON_INSTRUMENT_KEY,
        BATCH.SEQ_RUN_LOG.nextval as RUN_LOG_ID,
        enriched.COUNTRY_CODE as SABRE_COUNTRY_CODE,
	COALESCE(tc.TENOR_CURRENCY_KEY, -1) as TENOR_CURRENCY_KEY,
        COALESCE(td.TRADE_KEY, -1) as TRADE_KEY,
		COALESCE(NULLIF(td.SABRE_TRADE_CODE, ''), td.TRADE_CODE) as TRADE_NAME,
        td.TRADE_TYPOLOGY as TRADE_TYPOLOGY,
        NULL as ULTIMATE_PARENT,
        COALESCE(tim.ISIN, enriched.SECURITY_CODE) as UNDERLYING,
		enriched.UNDERLYING_TENOR_CODE as VERTEX_UNDERLYING,
        REPLACE(enriched.SECURITY_CODE, '.', '') as SABRE_SECURITY_CODE,
        NULL as SENIORITY,
		enriched.AMOUNT as AMOUNT_ORIGINAL,
        IFF(SUM(ABS(enriched.AMOUNT_IN_USD) + ABS(IFNULL(enriched.AMOUNT_IN_USD, 0))) OVER (PARTITION BY enriched.FRTBSA_SENSITIVITY_KEY) = 0, TRUE, FALSE) as IS_ZERO_FILTER
from enriched
left join DIMENSION.TRADE td
  on td.TRADE_CODE = NULLIF(enriched.TRADE_CODE, '')
	and td.ENTITY_CODE = enriched.ENTITY_CODE
	and TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') between td.EFFECTIVE_START_DATE and td.EFFECTIVE_END_DATE
left join DIMENSION.BOOK b
	on td.BOOK_CODE = b.BOOK_CODE
	and TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') between b.EFFECTIVE_START_DATE and b.EFFECTIVE_END_DATE
left join DIMENSION.MEASURE_TYPE mt
        on enriched.MEASURE_TYPE_CODE = mt.MEASURE_TYPE_CODE
left join DIMENSION.TENOR_CURRENCY tc
	on enriched.TENOR_CODE = tc.TENOR_CURRENCY_CODE
left join (
    select
        ticker,
        max(isin) as isin
    from STATIC_STAGING.TICKER_ISIN_MAP
    group by ticker
) tim
    on enriched.SECURITY_CODE = tim.ticker
left join DIMENSION.CURRENCY_PAIR cp
	on enriched.CURRENCY_PAIR_CODE = cp.CURRENCY_PAIR
left join DIMENSION.CURVE_CURRENCY cc
	on IFF(COALESCE(enriched.CURVE_TYPE, '') = '', 'N/A', enriched.CURVE_TYPE) = cc.CURVE_CODE
left join DIMENSION.COMMON_INSTRUMENT ci
	on NULLIF(enriched.SECURITY_CODE, '') = ci.INSTRUMENT_CODE
	and TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') between ci.EFFECTIVE_START_DATE and ci.EFFECTIVE_END_DATE
left join DIMENSION.COMMON_INSTRUMENT ci2
	on td.INSTRUMENT_KEY = ci2.INSTRUMENT_KEY
	and TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') between ci2.EFFECTIVE_START_DATE and ci2.EFFECTIVE_END_DATE
left join DIMENSION.COMMON_INSTRUMENT_FCD fci
	on NULLIF(enriched.SECURITY_CODE, '') = fci.INSTRUMENT_CODE
	and fci.IS_CURRENT_ROW = TRUE
left join DIMENSION.COMMON_INSTRUMENT_FCD fci2
	on td.INSTRUMENT_KEY = fci2.INSTRUMENT_KEY
	and fci2.IS_CURRENT_ROW = TRUE
left join DIMENSION.FRTB_INSTRUMENT fi
	on COALESCE(NULLIF(enriched.SECURITY_CODE, ''), 'NA') = fi.FRTB_INSTRUMENT_CODE
	and COALESCE(NULLIF(enriched.ISSUER_CODE, ''), 'NA') = fi.FRTB_ISSUER_CODE
	and TO_DATE(enriched.COBID::varchar, 'YYYYMMDD') between fi.EFFECTIVE_START_DATE and fi.EFFECTIVE_END_DATE;











