create or replace view DVLP_RAPTOR_NEWADJ.STAGING.IDM_SCALING_ADJUSTMENT_STREAM_DATA(
	COBID,
	PROCESS_TYPE,
	ADJUSTMENT_OCCURRENCE,
	ADJUSTMENT_TYPE,
	SOURCE_COBID,
	ENTITY_CODE,
	SOURCE_SYSTEM_CODE,
	DEPARTMENT_CODE,
	BOOK_CODE,
	CURRENCY_CODE,
	ADJUSTMENT_VALUE_IN_USD,
	CREATED_DATE,
	USERNAME,
	REASON,
	TRADE_TYPOLOGY,
	TRADE_CODE,
	SCALE_FACTOR,
	TRADER_CODE,
	VAR_COMPONENT_ID,
	VAR_SUB_COMPONENT_ID,
	SCENARIO_DATE_ID,
	APPROVAL_ID,
	GUARANTEED_ENTITY,
	STRATEGY,
	REGION_KEY,
	GLOBAL_ID,
	IS_DELETED,
	INSTRUMENT_CODE,
	SIMULATION_NAME,
	PRODUCT_CATEGORY_ATTRIBUTES,
	IS_10DAY,
	RUN_STATUS,
	SIMULATION_SOURCE,
	DAY_TYPE,
	CURVE_CODE,
	MEASURE_TYPE_CODE,
	TENOR_CODE,
	UNDERLYING_TENOR_CODE
) as
WITH ADJUSTMENT_LAST_VERSION AS (
	SELECT COBID, GLOBAL_ID, MAX(RAVEN_STAGE_TIMESTAMP) RAVEN_STAGE_TIMESTAMP
	FROM STAGING.IDM_SCALING_ADJUSTMENT_STREAM
	GROUP BY COBID, GLOBAL_ID
)
,ADJUSTMENT_TRACK AS (
	SELECT 
	    COBID, PROCESS_TYPE, ADJUSTMENT_OCCURRENCE, ADJUSTMENT_TYPE, SOURCE_COBID, ENTITY_CODE, SOURCE_SYSTEM_CODE, 
		DEPARTMENT_CODE, BOOK_CODE, CURRENCY_CODE, ADJUSTMENT_VALUE_IN_USD, CREATED_DATE, 
		USERNAME, REASON, TRADE_TYPOLOGY, 
		TRADE_CODE, SCALE_FACTOR, TRADER_CODE, ST.VAR_COMPONENT_ID, ST.VAR_SUB_COMPONENT_ID, 
		SCENARIO_DATE_ID, APPROVAL_ID, GUARANTEED_ENTITY, STRATEGY, REGION_KEY, GLOBAL_ID,  
		IFF(ACTIVE_STATUS = 'Deleted', TRUE, FALSE) IS_DELETED,
		INSTRUMENT_CODE, SIMULATION_NAME, PRODUCT_CATEGORY_ATTRIBUTES,
        CASE 
                     WHEN SC.VAR_SUB_COMPONENT_ID IS NOT NULL THEN 'Y'
                     WHEN SC1.VAR_COMPONENT_ID IS NOT NULL THEN 'Y'
                     WHEN SC1.VAR_COMPONENT_ID = 11 THEN 'Y'
                     ELSE 'N'
              END AS IS_10DAY,
        SIMULATION_SOURCE,
		DAY_TYPE,
		CURVE_CODE,
		MEASURE_TYPE_CODE,
		TENOR_CODE,
		UNDERLYING_TENOR_CODE
	FROM STAGING.IDM_SCALING_ADJUSTMENT_STREAM ST
           LEFT JOIN DIMENSION.VAR_SUB_COMPONENT SC
              ON ST.VAR_SUB_COMPONENT_ID = SC.VAR_SUB_COMPONENT_ID
              AND SC.VAR_SUB_COMPONENT_DAY_TYPE = 10
       LEFT JOIN (
              SELECT DISTINCT C.VAR_COMPONENT_ID
              FROM DIMENSION.VAR_SUB_COMPONENT C 
              WHERE C.VAR_SUB_COMPONENT_DAY_TYPE = 10
              UNION
              SELECT 11 /*for VarComponent = 10Day VaR*/
              ) AS SC1
                     ON SC1.VAR_COMPONENT_ID = ST.VAR_COMPONENT_ID 
   WHERE EXISTS (SELECT 1 
  				  FROM ADJUSTMENT_LAST_VERSION LV
  				 WHERE LV.COBID = ST.COBID
   				   AND LV.GLOBAL_ID = ST.GLOBAL_ID
   				   AND LV.RAVEN_STAGE_TIMESTAMP = ST.RAVEN_STAGE_TIMESTAMP
   				)
     AND METADATA$ACTION = 'INSERT'
     AND METADATA$ISUPDATE = 'FALSE'
	EXCEPT
	SELECT 
		COBID, PROCESS_TYPE, ADJUSTMENT_OCCURRENCE, ADJUSTMENT_TYPE, SOURCE_COBID, ENTITY_CODE, SOURCE_SYSTEM_CODE, 
		DEPARTMENT_CODE, BOOK_CODE, CURRENCY_CODE, ADJUSTMENT_VALUE_IN_USD, CREATED_DATE, 
		USERNAME, REASON, TRADE_TYPOLOGY, 
		TRADE_CODE, SCALE_FACTOR, TRADER_CODE, A.VAR_COMPONENT_ID, A.VAR_SUB_COMPONENT_ID, 
		SCENARIO_DATE_ID, APPROVAL_ID, GUARANTEED_ENTITY, STRATEGY, REGION_KEY, GLOBAL_REFERENCE, 
		IS_DELETED,
		INSTRUMENT_CODE, SIMULATION_NAME, PRODUCT_CATEGORY_ATTRIBUTES,
        CASE 
                     WHEN SC.VAR_SUB_COMPONENT_ID IS NOT NULL THEN 'Y'
                     WHEN SC1.VAR_COMPONENT_ID IS NOT NULL THEN 'Y'
                     WHEN SC1.VAR_COMPONENT_ID = 11 THEN 'Y'
                     ELSE 'N'
              END AS IS_10DAY,
        SIMULATION_SOURCE,
		DAY_TYPE,
		CURVE_CODE,
		MEASURE_TYPE_CODE,
		TENOR_CODE,
		UNDERLYING_TENOR_CODE
	FROM DIMENSION.ADJUSTMENT A
     LEFT JOIN DIMENSION.VAR_SUB_COMPONENT SC
              ON A.VAR_SUB_COMPONENT_ID = SC.VAR_SUB_COMPONENT_ID
              AND SC.VAR_SUB_COMPONENT_DAY_TYPE = 10
       LEFT JOIN (
              SELECT DISTINCT C.VAR_COMPONENT_ID
              FROM DIMENSION.VAR_SUB_COMPONENT C 
              WHERE C.VAR_SUB_COMPONENT_DAY_TYPE = 10
              UNION
              SELECT 11 /*for VarComponent = 10Day VaR*/
              ) AS SC1
                     ON SC1.VAR_COMPONENT_ID = A.VAR_COMPONENT_ID 
)
SELECT DL.COBID,
	DL.PROCESS_TYPE,
	DL.ADJUSTMENT_OCCURRENCE,
	DL.ADJUSTMENT_TYPE,
	DL.SOURCE_COBID,
	DL.ENTITY_CODE,
	DL.SOURCE_SYSTEM_CODE,
	DL.DEPARTMENT_CODE,
	DL.BOOK_CODE,
	DL.CURRENCY_CODE,
	DL.ADJUSTMENT_VALUE_IN_USD,
	DL.CREATED_DATE,
	DL.USERNAME,
	DL.REASON,
	DL.TRADE_TYPOLOGY,
	DL.TRADE_CODE,
	DL.SCALE_FACTOR,
	DL.TRADER_CODE,
	DL.VAR_COMPONENT_ID,
	DL.VAR_SUB_COMPONENT_ID,
	DL.SCENARIO_DATE_ID,
	DL.APPROVAL_ID,
	DL.GUARANTEED_ENTITY,
	DL.STRATEGY,
	DL.REGION_KEY,
	DL.GLOBAL_ID,
	DL.IS_DELETED,
	DL.INSTRUMENT_CODE,
	DL.SIMULATION_NAME,
	DL.PRODUCT_CATEGORY_ATTRIBUTES,
	DL.IS_10DAY,
	CASE 
		WHEN DL.PROCESS_TYPE NOT IN ('Sensitivity','FRTB') THEN
			CASE WHEN PVSO.PUBLISH_STATUS IS NULL THEN 'Pending' 
	             WHEN DL.IS_10DAY = 'Y' THEN 'Pending'
	             ELSE 'Rejected - SignedOff' 
	        END 
		WHEN DL.PROCESS_TYPE IN ('Sensitivity','FRTB') THEN
			CASE WHEN PSOE.PUBLISH_STATUS IS NULL THEN 'Pending' 
	              ELSE 'Rejected - SignedOff' 
	         END 
	    ELSE 'Pending'
    END AS RUN_STATUS,
    DL.SIMULATION_SOURCE,
	DL.DAY_TYPE,	
	DL.CURVE_CODE,
	DL.MEASURE_TYPE_CODE,
	DL.TENOR_CODE,
	DL.UNDERLYING_TENOR_CODE
FROM ADJUSTMENT_TRACK DL
LEFT JOIN BATCH.PUBLISH_VAR_SIGNOFF_STATUS PVSO 
	 ON DL.COBID = PVSO.COBID 
	AND DL.ENTITY_CODE = PVSO.ENTITY_CODE
	AND DL.PROCESS_TYPE = 'VaR'
	AND PVSO.PUBLISH_STATUS = 'SignedOff'
LEFT JOIN BATCH.PUBLISH_SIGNOFF_STATUS_EXCEPTION PSOE
	 ON DL.COBID = PSOE.COBID 
	AND DL.ENTITY_CODE = PSOE.ENTITY_CODE
	AND DL.PROCESS_TYPE = PSOE.PROCESS_TYPE
	AND PSOE.SUB_TYPE  ='NonCVA'
	AND PSOE.PUBLISH_STATUS = 'SignedOff';