-- =============================================================================
-- ALL SCOPES — dev vs prod, one row per (adjustment, source).  Export → pivot.
-- =============================================================================
-- Lists every adjustment posted in the app that is Processed and not deleted,
-- and the impact it wrote to the *_ADJUSTMENT (delta) table in BOTH databases:
--   • dev  = DVLP_RAPTOR_NEWADJ  — matched by DIMENSION_ADJ_ID
--   • prod = PROD_RAPTOR         — matched by the PROD adjustment id the user
--                                  typed in the Reason / Justification field
--                                  (the first number found in Reason is used).
--
-- Run with a session that can read BOTH databases.
-- Excel pivot: rows = COBID / ENTITY / PROCESS_TYPE / PROD_ADJ_ID,
--              columns = SOURCE, values = TOTAL_ADJUSTMENT  (dev vs prod side by side).
-- =============================================================================

WITH app_adj AS (
    -- Every app adjustment that finished processing (not deleted).
    SELECT
        h.DIMENSION_ADJ_ID                                AS DEV_ADJ_ID,
        TRY_TO_NUMBER(REGEXP_SUBSTR(h.REASON, '[0-9]+'))  AS PROD_ADJ_ID,  -- prod id from Reason
        h.COBID, h.SOURCE_COBID,
        h.ENTITY_CODE                                     AS ENTITY,
        h.PROCESS_TYPE, h.ADJUSTMENT_TYPE
    FROM DVLP_RAPTOR_NEWADJ.ADJUSTMENT_APP.ADJ_HEADER h
    WHERE h.RUN_STATUS = 'Processed'
      AND h.IS_DELETED = FALSE
      AND h.DIMENSION_ADJ_ID IS NOT NULL
),

dev_fact AS (   -- rows + total per dev adjustment, from DEV *_ADJUSTMENT tables
    SELECT 'VaR' AS PROCESS_TYPE, ADJUSTMENT_ID AS ADJ_ID,
           COUNT(*) AS ROWS_COUNT, SUM(PNL_VECTOR_VALUE_IN_USD) AS TOTAL_ADJUSTMENT
    FROM DVLP_RAPTOR_NEWADJ.FACT.VAR_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Stress', ADJUSTMENT_ID, COUNT(*), SUM(SIMULATION_PL_IN_USD)
    FROM DVLP_RAPTOR_NEWADJ.FACT.STRESS_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Sensitivity', ADJUSTMENT_ID, COUNT(*), SUM(MEASURE_VALUE_USD)
    FROM DVLP_RAPTOR_NEWADJ.FACT.SENSITIVITY_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTB', ADJUSTMENT_ID, COUNT(*), SUM(AMOUNT_IN_USD)
    FROM DVLP_RAPTOR_NEWADJ.FACT.FRTBSA_SENSITIVITY_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBDRC', ADJUSTMENT_ID, COUNT(*), SUM(JTD_LOSS_USD)
    FROM DVLP_RAPTOR_NEWADJ.FACT.FRTBSA_DRC_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBRRAO', ADJUSTMENT_ID, COUNT(*), SUM(NOTIONAL_AMOUNT_USD)
    FROM DVLP_RAPTOR_NEWADJ.FACT.FRTBSA_RRAO_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
),

prod_fact AS (  -- rows + total per prod adjustment, from PROD *_ADJUSTMENT tables
    SELECT 'VaR' AS PROCESS_TYPE, ADJUSTMENT_ID AS ADJ_ID,
           COUNT(*) AS ROWS_COUNT, SUM(PNL_VECTOR_VALUE_IN_USD) AS TOTAL_ADJUSTMENT
    FROM PROD_RAPTOR.FACT.VAR_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Stress', ADJUSTMENT_ID, COUNT(*), SUM(SIMULATION_PL_IN_USD)
    FROM PROD_RAPTOR.FACT.STRESS_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Sensitivity', ADJUSTMENT_ID, COUNT(*), SUM(MEASURE_VALUE_USD)
    FROM PROD_RAPTOR.FACT.SENSITIVITY_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTB', ADJUSTMENT_ID, COUNT(*), SUM(AMOUNT_IN_USD)
    FROM PROD_RAPTOR.FACT.FRTBSA_SENSITIVITY_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBDRC', ADJUSTMENT_ID, COUNT(*), SUM(JTD_LOSS_USD)
    FROM PROD_RAPTOR.FACT.FRTBSA_DRC_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBRRAO', ADJUSTMENT_ID, COUNT(*), SUM(NOTIONAL_AMOUNT_USD)
    FROM PROD_RAPTOR.FACT.FRTBSA_RRAO_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID IN (SELECT PROD_ADJ_ID FROM app_adj) GROUP BY ADJUSTMENT_ID
)

SELECT 'dev'  AS SOURCE,
       a.COBID, a.SOURCE_COBID, a.ENTITY, a.PROCESS_TYPE, a.ADJUSTMENT_TYPE,
       COALESCE(d.ROWS_COUNT, 0)        AS ROWS_COUNT,
       COALESCE(d.TOTAL_ADJUSTMENT, 0)  AS TOTAL_ADJUSTMENT,
       a.DEV_ADJ_ID                     AS ADJUSTMENT_ID,
       a.PROD_ADJ_ID
FROM app_adj a
LEFT JOIN dev_fact d
       ON d.PROCESS_TYPE = a.PROCESS_TYPE AND d.ADJ_ID = a.DEV_ADJ_ID

UNION ALL

SELECT 'prod' AS SOURCE,
       a.COBID, a.SOURCE_COBID, a.ENTITY, a.PROCESS_TYPE, a.ADJUSTMENT_TYPE,
       COALESCE(p.ROWS_COUNT, 0)        AS ROWS_COUNT,
       COALESCE(p.TOTAL_ADJUSTMENT, 0)  AS TOTAL_ADJUSTMENT,
       a.PROD_ADJ_ID                    AS ADJUSTMENT_ID,
       a.PROD_ADJ_ID
FROM app_adj a
LEFT JOIN prod_fact p
       ON p.PROCESS_TYPE = a.PROCESS_TYPE AND p.ADJ_ID = a.PROD_ADJ_ID

ORDER BY PROCESS_TYPE, COBID, PROD_ADJ_ID, SOURCE;
