[theme]
primaryColor = "#D50032"
backgroundColor = "#F7F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2D2D2D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
