-- ═══════════════════════════════════════════════════════════════════════════
-- Adjustment reconciliation v2
--
-- Fixes vs v1:
--  1. Dimension filters mirror the engine exactly: EXISTS with
--     COALESCE(key,-1), applied ONLY when the adjustment set that filter.
--     v1's unconditional INNER JOINs to BOOK/TRADE/COMMON_INSTRUMENT dropped
--     fact rows with NULL/orphan keys → false BREAKs (811696, 811722).
--  2. Scale: expected delta is ORIGINAL*(FACTOR-1), not av+ORIGINAL*FACTOR
--     (v1's formula is only zero at factor=0.5 — its one green Scale row
--     passed by coincidence). Factor=1 → zero delta → engine writes no rows:
--     reported as NO-OP, not MISSING.
--  3. Cross-day Scale (SOURCE_COBID <> COBID): delta = adjusted(source)*factor
--     (engine stamps SCALE_FACTOR_ADJUSTED = factor for these).
--  4. Roll: invariant checked is combined(target) = adjusted(source) — robust
--     to pre-existing adjustments at the target COB, which v1 ignored.
--  5. Sensitivity MEASURE_TYPE_CODE is now honoured (via DIMENSION.MEASURE_TYPE
--     on MEASURE_TYPE_KEY — the sensitivity fact has no code column).
--  6. Everything is keyed per DEV_ADJ_ID — no scope-level GROUP BY that can
--     lump two same-scope adjustments together.
--  7. Status separates NO DATA IN SCOPE (both sides empty — filter matched
--     nothing; check the filter values) and NO-OP from real MISSING/BREAK.
--
-- Not modelled (none of the current test adjustments use them): VaR
-- component/day-type filters, tenor/curve/PCA filters, SOURCE_SYSTEM_CODE.
-- ═══════════════════════════════════════════════════════════════════════════

WITH adj AS (
    SELECT
        h.ADJ_ID,
        h.DIMENSION_ADJ_ID      AS DEV_ADJ_ID,
        h.COBID,
        h.SOURCE_COBID,
        h.PROCESS_TYPE,
        h.ADJUSTMENT_TYPE,
        h.ENTITY_CODE,
        h.DEPARTMENT_CODE,
        h.BOOK_CODE,
        h.TRADE_CODE,
        h.TRADE_TYPOLOGY,
        h.STRATEGY,
        h.INSTRUMENT_CODE,
        h.SIMULATION_NAME,
        h.SIMULATION_SOURCE,
        h.MEASURE_TYPE_CODE,
        h.SCALE_FACTOR,
        h.ADJUSTMENT_VALUE_IN_USD,
        h.RECORD_COUNT,
        h.REASON
    FROM ADJUSTMENT_APP.ADJ_HEADER h
    WHERE h.RUN_STATUS = 'Processed'
      AND h.IS_DELETED = FALSE
      AND h.DIMENSION_ADJ_ID IS NOT NULL
      AND DAYNAME(TO_DATE(h.SOURCE_COBID::STRING, 'yyyyMMdd')) NOT IN ('Sat','Sun')
      AND h.ADJUSTMENT_TYPE <> 'EROL'
      AND h.ADJUSTMENT_TYPE <> 'Upload'
),

-- ── What the engine actually wrote, per adjustment id ────────────────────
adjustment_values AS (
    SELECT 'VaR' AS PROCESS_TYPE, ADJUSTMENT_ID, SUM(PNL_VECTOR_VALUE_IN_USD) AS ADJUSTMENT_VALUE
      FROM FACT.VAR_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Stress', ADJUSTMENT_ID, SUM(SIMULATION_PL_IN_USD)
      FROM FACT.STRESS_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'Sensitivity', ADJUSTMENT_ID, SUM(MEASURE_VALUE_USD)
      FROM FACT.SENSITIVITY_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTB', ADJUSTMENT_ID, SUM(AMOUNT_IN_USD)
      FROM FACT.FRTBSA_SENSITIVITY_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBDRC', ADJUSTMENT_ID, SUM(JTD_LOSS_USD)
      FROM FACT.FRTBSA_DRC_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
    UNION ALL
    SELECT 'FRTBRRAO', ADJUSTMENT_ID, SUM(NOTIONAL_AMOUNT_USD)
      FROM FACT.FRTBSA_RRAO_MEASURES_ADJUSTMENT
     WHERE ADJUSTMENT_ID IN (SELECT DEV_ADJ_ID FROM adj) GROUP BY ADJUSTMENT_ID
),

-- ── ORIGINAL at target COB (Flatten / same-day Scale baseline) ───────────
-- Filter predicates mirror 05_sp_process_adjustment: EXISTS on the dimension
-- with COALESCE(key,-1), and the whole EXISTS is skipped when the adjustment
-- did not set any of the mapped filters (so NULL-key fact rows stay in).
original_values AS (
    -- VaR
    SELECT a.DEV_ADJ_ID, SUM(f.PNL_VECTOR_VALUE_IN_USD) AS ORIGINAL_VALUE
    FROM adj a
    JOIN FACT.VAR_MEASURES f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'VaR'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    -- Stress
    SELECT a.DEV_ADJ_ID, SUM(f.SIMULATION_PL_IN_USD)
    FROM adj a
    JOIN FACT.STRESS_MEASURES f
      ON f.COBID = a.COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND ((a.SIMULATION_NAME IS NULL AND a.SIMULATION_SOURCE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.STRESS_SIMULATION ss
            WHERE ss.STRESS_SIMULATION_KEY = COALESCE(f.STRESS_SIMULATION_KEY, -1)
              AND (ss.STRESS_SIMULATION_NAME = a.SIMULATION_NAME OR a.SIMULATION_NAME IS NULL)
              AND (ss.SIMULATION_SOURCE = a.SIMULATION_SOURCE OR a.SIMULATION_SOURCE IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Stress'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    -- Sensitivity (measure type via DIMENSION.MEASURE_TYPE — fact has KEY only)
    SELECT a.DEV_ADJ_ID, SUM(f.MEASURE_VALUE_USD)
    FROM adj a
    JOIN FACT.SENSITIVITY_MEASURES f
      ON f.COBID = a.COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Sensitivity'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    -- FRTB (measure type: direct code AND dimension key, mirroring the engine)
    SELECT a.DEV_ADJ_ID, SUM(f.AMOUNT_IN_USD)
    FROM adj a
    JOIN FACT.FRTBSA_SENSITIVITY_MEASURES f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR f.INSTRUMENT_CODE = a.INSTRUMENT_CODE)
    WHERE a.PROCESS_TYPE = 'FRTB'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    -- FRTBDRC
    SELECT a.DEV_ADJ_ID, SUM(f.JTD_LOSS_USD)
    FROM adj a
    JOIN FACT.FRTBSA_DRC_MEASURES f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBDRC'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    -- FRTBRRAO
    SELECT a.DEV_ADJ_ID, SUM(f.NOTIONAL_AMOUNT_USD)
    FROM adj a
    JOIN FACT.FRTBSA_RRAO_MEASURES f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBRRAO'
    GROUP BY a.DEV_ADJ_ID
),

-- ── ADJUSTED value at the SOURCE COB (Roll + cross-day Scale) ────────────
-- Same predicates as original_values, but against the combined/adjusted view
-- at SOURCE_COBID. Membership: Roll, or Scale with SOURCE_COBID <> COBID.
source_values AS (
    SELECT a.DEV_ADJ_ID, SUM(f.PNL_VECTOR_VALUE_IN_USD) AS SOURCE_VALUE
    FROM adj a
    JOIN FACT.VAR_MEASURES_COMBINED f
      ON f.COBID = a.SOURCE_COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'VaR'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.SIMULATION_PL_IN_USD)
    FROM adj a
    JOIN FACT.STRESS_MEASURES_COMBINED f
      ON f.COBID = a.SOURCE_COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND ((a.SIMULATION_NAME IS NULL AND a.SIMULATION_SOURCE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.STRESS_SIMULATION ss
            WHERE ss.STRESS_SIMULATION_KEY = COALESCE(f.STRESS_SIMULATION_KEY, -1)
              AND (ss.STRESS_SIMULATION_NAME = a.SIMULATION_NAME OR a.SIMULATION_NAME IS NULL)
              AND (ss.SIMULATION_SOURCE = a.SIMULATION_SOURCE OR a.SIMULATION_SOURCE IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Stress'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.MEASURE_VALUE_USD)
    FROM adj a
    JOIN FACT.SENSITIVITY_MEASURES_ADJUSTED f
      ON f.COBID = a.SOURCE_COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Sensitivity'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.AMOUNT_IN_USD)
    FROM adj a
    JOIN FACT.FRTBSA_SENSITIVITY_MEASURES_ADJUSTED f
      ON f.COBID = a.SOURCE_COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR f.INSTRUMENT_CODE = a.INSTRUMENT_CODE)
    WHERE a.PROCESS_TYPE = 'FRTB'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.JTD_LOSS_USD)
    FROM adj a
    JOIN FACT.FRTBSA_DRC_MEASURES_ADJUSTED f
      ON f.COBID = a.SOURCE_COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBDRC'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.NOTIONAL_AMOUNT_USD)
    FROM adj a
    JOIN FACT.FRTBSA_RRAO_MEASURES_ADJUSTED f
      ON f.COBID = a.SOURCE_COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBRRAO'
      AND (a.ADJUSTMENT_TYPE = 'Roll' OR (a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID <> a.COBID))
    GROUP BY a.DEV_ADJ_ID
),

-- ── COMBINED value at the TARGET COB (Roll invariant check) ──────────────
-- Roll promise: combined(target) = adjusted(source). Comparing these two
-- directly is robust to pre-existing adjustments at the target COB.
target_combined AS (
    SELECT a.DEV_ADJ_ID, SUM(f.PNL_VECTOR_VALUE_IN_USD) AS TARGET_COMBINED_VALUE
    FROM adj a
    JOIN FACT.VAR_MEASURES_COMBINED f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'VaR' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.SIMULATION_PL_IN_USD)
    FROM adj a
    JOIN FACT.STRESS_MEASURES_COMBINED f
      ON f.COBID = a.COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND ((a.SIMULATION_NAME IS NULL AND a.SIMULATION_SOURCE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.STRESS_SIMULATION ss
            WHERE ss.STRESS_SIMULATION_KEY = COALESCE(f.STRESS_SIMULATION_KEY, -1)
              AND (ss.STRESS_SIMULATION_NAME = a.SIMULATION_NAME OR a.SIMULATION_NAME IS NULL)
              AND (ss.SIMULATION_SOURCE = a.SIMULATION_SOURCE OR a.SIMULATION_SOURCE IS NULL)))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Stress' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.MEASURE_VALUE_USD)
    FROM adj a
    JOIN FACT.SENSITIVITY_MEASURES_ADJUSTED f
      ON f.COBID = a.COBID
     AND EXISTS (SELECT 1 FROM DIMENSION.ENTITY e
                 WHERE e.ENTITY_KEY = COALESCE(f.ENTITY_KEY, -1)
                   AND e.ENTITY_CODE = a.ENTITY_CODE)
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.COMMON_INSTRUMENT ci
            WHERE ci.COMMON_INSTRUMENT_KEY = COALESCE(f.COMMON_INSTRUMENT_KEY, -1)
              AND ci.INSTRUMENT_CODE = a.INSTRUMENT_CODE))
    WHERE a.PROCESS_TYPE = 'Sensitivity' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.AMOUNT_IN_USD)
    FROM adj a
    JOIN FACT.FRTBSA_SENSITIVITY_MEASURES_ADJUSTED f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
     AND (a.MEASURE_TYPE_CODE IS NULL OR EXISTS (
            SELECT 1 FROM DIMENSION.MEASURE_TYPE mt
            WHERE mt.MEASURE_TYPE_KEY = COALESCE(f.MEASURE_TYPE_KEY, -1)
              AND mt.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE))
     AND (a.INSTRUMENT_CODE IS NULL OR f.INSTRUMENT_CODE = a.INSTRUMENT_CODE)
    WHERE a.PROCESS_TYPE = 'FRTB' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.JTD_LOSS_USD)
    FROM adj a
    JOIN FACT.FRTBSA_DRC_MEASURES_ADJUSTED f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBDRC' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID

    UNION ALL
    SELECT a.DEV_ADJ_ID, SUM(f.NOTIONAL_AMOUNT_USD)
    FROM adj a
    JOIN FACT.FRTBSA_RRAO_MEASURES_ADJUSTED f
      ON f.COBID = a.COBID
     AND f.ENTITY_CODE = a.ENTITY_CODE
     AND ((a.BOOK_CODE IS NULL AND a.DEPARTMENT_CODE IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.BOOK bk
            WHERE bk.BOOK_KEY = COALESCE(f.BOOK_KEY, -1)
              AND (bk.BOOK_CODE = a.BOOK_CODE OR a.BOOK_CODE IS NULL)
              AND (bk.DEPARTMENT_CODE = a.DEPARTMENT_CODE OR a.DEPARTMENT_CODE IS NULL)))
     AND ((a.TRADE_CODE IS NULL AND a.TRADE_TYPOLOGY IS NULL AND a.STRATEGY IS NULL) OR EXISTS (
            SELECT 1 FROM DIMENSION.TRADE td
            WHERE td.TRADE_KEY = COALESCE(f.TRADE_KEY, -1)
              AND (td.TRADE_CODE = a.TRADE_CODE OR a.TRADE_CODE IS NULL)
              AND (td.TRADE_TYPOLOGY = a.TRADE_TYPOLOGY OR a.TRADE_TYPOLOGY IS NULL)
              AND (td.STRATEGY = a.STRATEGY OR a.STRATEGY IS NULL)))
     AND (a.MEASURE_TYPE_CODE IS NULL OR f.MEASURE_TYPE_CODE = a.MEASURE_TYPE_CODE)
    WHERE a.PROCESS_TYPE = 'FRTBRRAO' AND a.ADJUSTMENT_TYPE = 'Roll'
    GROUP BY a.DEV_ADJ_ID
)

SELECT
    a.DEV_ADJ_ID,
    a.COBID,
    a.PROCESS_TYPE,
    a.ADJUSTMENT_TYPE,
    a.ENTITY_CODE,
    a.DEPARTMENT_CODE,
    a.BOOK_CODE,
    a.TRADE_CODE,
    a.TRADE_TYPOLOGY,
    a.INSTRUMENT_CODE,
    a.SIMULATION_NAME,
    a.MEASURE_TYPE_CODE,
    a.SCALE_FACTOR,
    a.SOURCE_COBID,
    a.RECORD_COUNT,                       -- caution: shared per run batch, not per adj
    av.ADJUSTMENT_VALUE,
    o.ORIGINAL_VALUE,
    s.SOURCE_VALUE,
    tc.TARGET_COMBINED_VALUE,
    -- Expected DELTA the engine should have written
    CASE
        WHEN a.ADJUSTMENT_TYPE = 'Direct' THEN a.ADJUSTMENT_VALUE_IN_USD
        WHEN a.ADJUSTMENT_TYPE = 'Flatten' THEN -o.ORIGINAL_VALUE
        WHEN a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID = a.COBID
             THEN o.ORIGINAL_VALUE * (a.SCALE_FACTOR - 1)
        WHEN a.ADJUSTMENT_TYPE = 'Scale'                       -- cross-day scale
             THEN s.SOURCE_VALUE * a.SCALE_FACTOR
        WHEN a.ADJUSTMENT_TYPE = 'Roll'
             THEN s.SOURCE_VALUE - (tc.TARGET_COMBINED_VALUE - av.ADJUSTMENT_VALUE)
    END AS EXPECTED_ADJ_VALUE,
    CASE
        WHEN a.ADJUSTMENT_TYPE = 'Direct'
             THEN av.ADJUSTMENT_VALUE - a.ADJUSTMENT_VALUE_IN_USD
        WHEN a.ADJUSTMENT_TYPE = 'Roll'
             THEN tc.TARGET_COMBINED_VALUE - s.SOURCE_VALUE    -- invariant: combined(target)=adjusted(source)
        WHEN a.ADJUSTMENT_TYPE = 'Flatten'
             THEN av.ADJUSTMENT_VALUE + o.ORIGINAL_VALUE
        WHEN a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID = a.COBID
             THEN av.ADJUSTMENT_VALUE - o.ORIGINAL_VALUE * (a.SCALE_FACTOR - 1)
        WHEN a.ADJUSTMENT_TYPE = 'Scale'
             THEN av.ADJUSTMENT_VALUE - s.SOURCE_VALUE * a.SCALE_FACTOR
    END AS RECON_DIFFERENCE,
    CASE
        WHEN a.ADJUSTMENT_TYPE = 'Direct' THEN
            CASE
                WHEN a.ADJUSTMENT_VALUE_IN_USD IS NULL THEN 'LEGACY DIRECT (pre-split) — not comparable'
                WHEN av.ADJUSTMENT_VALUE IS NULL THEN 'MISSING ADJUSTMENT'
                WHEN ABS(av.ADJUSTMENT_VALUE - a.ADJUSTMENT_VALUE_IN_USD) < 0.01
                     THEN 'RECONCILED'
                ELSE 'BREAK'
            END
        WHEN a.ADJUSTMENT_TYPE = 'Roll' THEN
            CASE
                WHEN s.SOURCE_VALUE IS NULL AND av.ADJUSTMENT_VALUE IS NULL
                     THEN 'NO DATA IN SCOPE (check filter values)'
                WHEN s.SOURCE_VALUE IS NULL          THEN 'MISSING ROLL SOURCE'
                WHEN tc.TARGET_COMBINED_VALUE IS NULL THEN 'MISSING TARGET DATA'
                WHEN ABS(tc.TARGET_COMBINED_VALUE - s.SOURCE_VALUE) < 0.01
                     THEN 'RECONCILED'
                ELSE 'BREAK'
            END
        WHEN a.ADJUSTMENT_TYPE = 'Scale' AND a.SOURCE_COBID = a.COBID THEN
            CASE
                WHEN o.ORIGINAL_VALUE IS NULL AND av.ADJUSTMENT_VALUE IS NULL
                     THEN 'NO DATA IN SCOPE (check filter values)'
                WHEN av.ADJUSTMENT_VALUE IS NULL
                     AND ABS(COALESCE(o.ORIGINAL_VALUE,0) * (a.SCALE_FACTOR - 1)) < 0.01
                     THEN 'NO-OP (zero delta, factor=1)'
                WHEN av.ADJUSTMENT_VALUE IS NULL     THEN 'MISSING ADJUSTMENT'
                WHEN o.ORIGINAL_VALUE IS NULL        THEN 'MISSING ORIGINAL'
                WHEN ABS(av.ADJUSTMENT_VALUE - o.ORIGINAL_VALUE * (a.SCALE_FACTOR - 1)) < 0.01
                     THEN 'RECONCILED'
                ELSE 'BREAK'
            END
        WHEN a.ADJUSTMENT_TYPE = 'Scale' THEN        -- cross-day scale
            CASE
                WHEN s.SOURCE_VALUE IS NULL AND av.ADJUSTMENT_VALUE IS NULL
                     THEN 'NO DATA IN SCOPE (check filter values)'
                WHEN av.ADJUSTMENT_VALUE IS NULL     THEN 'MISSING ADJUSTMENT'
                WHEN s.SOURCE_VALUE IS NULL          THEN 'MISSING SOURCE'
                WHEN ABS(av.ADJUSTMENT_VALUE - s.SOURCE_VALUE * a.SCALE_FACTOR) < 0.01
                     THEN 'RECONCILED'
                ELSE 'BREAK'
            END
        ELSE -- Flatten
            CASE
                WHEN o.ORIGINAL_VALUE IS NULL AND av.ADJUSTMENT_VALUE IS NULL
                     THEN 'NO DATA IN SCOPE (check filter values)'
                WHEN av.ADJUSTMENT_VALUE IS NULL     THEN 'MISSING ADJUSTMENT'
                WHEN o.ORIGINAL_VALUE IS NULL        THEN 'MISSING ORIGINAL'
                WHEN ABS(av.ADJUSTMENT_VALUE + o.ORIGINAL_VALUE) < 0.01
                     THEN 'RECONCILED'
                ELSE 'BREAK'
            END
    END AS RECON_STATUS,
    a.REASON
FROM adj a
LEFT JOIN adjustment_values av ON av.PROCESS_TYPE = a.PROCESS_TYPE
                              AND av.ADJUSTMENT_ID = a.DEV_ADJ_ID
LEFT JOIN original_values  o  ON o.DEV_ADJ_ID  = a.DEV_ADJ_ID
LEFT JOIN source_values    s  ON s.DEV_ADJ_ID  = a.DEV_ADJ_ID
LEFT JOIN target_combined  tc ON tc.DEV_ADJ_ID = a.DEV_ADJ_ID
ORDER BY a.COBID, a.PROCESS_TYPE, a.DEV_ADJ_ID;
