WITH LATEST_PROCESS AS (
	SELECT 
	RAVEN_COBID AS COBID, 
	DATASET_NAME, 
	BATCH_MAPPING_CODE,
	MAX(START_TIMESTAMP) START_TIMESTAMP
	FROM RAVEN.LOG_STAGE_ME_STATUS S
	INNER JOIN BATCH.BATCH_ACTION_MAPPING M ON S.DATASET_NAME = SPLIT_PART(M.BATCH_ACTION_NAME, '.',1) COLLATE 'utf8'
	WHERE S.DATASET_NAME IN ('DUMMY_FRTB_Adjustment', 'DUMMY_Sensitivity_Adjustment')
	AND S.START_TIMESTAMP >= DATEADD('hour', -48, CURRENT_TIMESTAMP()) 
	GROUP BY ALL
)
SELECT count(*) AS DBT_TRIGGERS
FROM LATEST_PROCESS L
LEFT JOIN BATCH.BATCH_CONDITIONS C ON C.BATCH_MAPPING_CODE = L.BATCH_MAPPING_CODE 
								  AND C.COBID = L.COBID
WHERE C.APPLIED_FLAG = FALSE	