-- Verify a same-COB VaR Scale adjustment reconciles to the preview total.
-- After the exact-total rounding fix in SP_PROCESS_ADJUSTMENT (2026-09-14),
-- STORED_DELTA must equal ROUND(EXACT_DELTA, 4) and MATCHED_ROWS = ADJ_ROWS.
-- Replace <ADJ_ID>, <COBID> and the factor (0.95 → -0.05 = factor - 1).
WITH f AS (
    SELECT ENTITY_CODE, BOOK_KEY, TRADE_KEY, COMMON_INSTRUMENT_KEY,
           COMMON_INSTRUMENT_FCD_KEY, CURRENCY_CODE, SOURCE_SYSTEM_CODE,
           VAR_SUBCOMPONENT_ID, SCENARIO_DATE_ID, IS_OFFICIAL_SOURCE,
           SUM(PNL_VECTOR_VALUE_IN_USD) AS V
    FROM FACT.VAR_MEASURES
    WHERE COBID = <COBID>
    GROUP BY ALL
),
a AS (
    SELECT *
    FROM FACT.VAR_MEASURES_ADJUSTMENT
    WHERE ADJUSTMENT_ID = (SELECT DIMENSION_ADJ_ID
                           FROM ADJUSTMENT_APP.ADJ_HEADER
                           WHERE ADJ_ID = '<ADJ_ID>')
)
SELECT COUNT(*)                          AS ADJ_ROWS,
       COUNT(f.V)                        AS MATCHED_ROWS,
       SUM(a.PNL_VECTOR_VALUE_IN_USD)    AS STORED_DELTA,
       SUM(f.V)                          AS ORIGINAL_MATCHED,
       SUM(f.V) * -0.05                  AS EXACT_DELTA,
       ROUND(SUM(f.V) * -0.05, 4)        AS EXPECTED_STORED_DELTA,
       SUM(ROUND(f.V * -0.05, 4))        AS NAIVE_PER_ROW_DELTA   -- pre-fix behaviour
FROM a
LEFT JOIN f
  ON  EQUAL_NULL(f.ENTITY_CODE, a.ENTITY_CODE)
  AND EQUAL_NULL(f.BOOK_KEY, a.BOOK_KEY)
  AND EQUAL_NULL(f.TRADE_KEY, a.TRADE_KEY)
  AND EQUAL_NULL(f.COMMON_INSTRUMENT_KEY, a.COMMON_INSTRUMENT_KEY)
  AND EQUAL_NULL(f.COMMON_INSTRUMENT_FCD_KEY, a.COMMON_INSTRUMENT_FCD_KEY)
  AND EQUAL_NULL(f.CURRENCY_CODE, a.CURRENCY_CODE)
  AND EQUAL_NULL(f.SOURCE_SYSTEM_CODE, a.SOURCE_SYSTEM_CODE)
  AND EQUAL_NULL(f.VAR_SUBCOMPONENT_ID, a.VAR_SUBCOMPONENT_ID)
  AND EQUAL_NULL(f.SCENARIO_DATE_ID, a.SCENARIO_DATE_ID)
  AND EQUAL_NULL(f.IS_OFFICIAL_SOURCE, a.IS_OFFICIAL_SOURCE);
